### ISSUE TITLE
Fast navigation with relative line numbers

### ISSUE THREAD

**Issue by tannhuber** [ranger/ranger#101]
Since I am accustomed to vim's "numbers" plugin, see http://myusuf3.github.io/numbers.vim/, I would be very happy about a similar feature for ranger's active column. Line numbers, relative to the cursor position, allow to navigate very comfortable with counters.

**Comment by a13ph** [comment]
I think it's quite problematic, as you'd probably need to increase border of active pane on the fly, and there are already lots of characters optionally used: 

- on the right side there are vcs icons (usually 2, I guess) and directory file count/size 
- on the left side there are single-character tags

Relative-numbers would usually require 2, sometimes 3 digits, and 1+-1 spaces for readability.

Coloring line numbers distinctively might reduce need for additional spacing for readability purposes.

Having numbers always on and not only for an active pane would reduce flicker (changes in layout), but will increase clutter somewhat.

Reserving spacing for those line numbers in other panes would reduce flicker, but also would reduce the effective space.

Miller viewmode is less prone to those issues atm, since active pane is always in the same space, so no flickering by default.

**Comment by nfnty** [comment]
PRs are welcome.

**Comment by swalladge** [comment]
It looks like this is already implemented with the `line_numbers` setting.

**Comment by vimeitor** [comment]
It is, indeed. I'm not sure how long it has been there for, but it works as expected =)
So this issue can be closed.

**Comment by nfnty** [comment]
Yeah, missed that it was added in `1.8.0`.
