### ISSUE TITLE
Autostart ranger on i3wm can't open editor (subl3 or nano)

### ISSUE THREAD

**Issue by thyeun** [ranger/ranger#1126]
OS : Arch linux
Ranger : 1.9.1
python : 3.6.4
WM : i3wm

I have make ranger to autostart when login, once inside ranger and i'm triggering a txt file to open with ```subl3``` or ```nano``` it wont open the file by editor. instead that given me a message ```/bin/sh vim command not found```.

but if i'm mannualy open ranger using urxvt, meaning that i open urxvt terminal first than key-in ```ranger```, than i can open the same file with ```subl3``` or ```nano```.

so what am i missing out here?

p/s : i'm not using vim and not install it.

**Comment by thyeun** [comment]
solve it by myself

=.=

**Comment by toonn** [comment]
It's great that you solved it. Maybe describe your solution so people who come across your issue through google are helped.

**Comment by thyeun** [comment]
@toonn, sorry, i'm too excited because wasted almost 6 hours to figure it out, and forget to paste the solution here, my bad.

the solution i have is to put the below into /etc/environment 
```
export VISUAL=subl3
export EDITOR=subl3
```
i'm not sure it is the good practice or not, but i'm now possible to open editor with autostart ranger and key-binding open ranger on special workspace (with possible to open editor)  and for open as root no need to use ```sudo -E ranger``` to open ```subl3``` too, just normal ```sudo ranger``` will done the magic.

**Comment by toonn** [comment]
You only need to set `VISUAL` setting `EDITOR` to a visual file editor like vi as opposed to ed is technically wrong.
Setting it in `/etc/environment` will affect the entire system, including any other users on the system. Probably not a problem for you but something to keep in mind.
The most common place to set variables for your window manager is `~/.xprofile` afaik. Obviously that won't change the settings for root but that's by design.

This problem showed up because you probably have similar lines in your `.bashrc` and i3wm doesn't load that file, it should load `.xprofile` though.

**Comment by thyeun** [comment]
@toonn ok, understand now, thank you so much.

**Comment by joelostblom** [comment]
I also had this issue on Antergos (Arch derivative) with i3 when trying to bind a hotkey to launch `ranger`. For me, it occurred because the Cnchi installer added `EDITOR=/usr/bin/vim` in both `/etc/environment` and `/etc/profile`when installing Antergos. Removing these lines resolved the issue.
