### ISSUE TITLE
image preview doesn't redraw the whole pic in konsole

### ISSUE THREAD

**Issue by hektr** [ranger/ranger#1154]
I use kde konsole and w3mimgdisplay on debian. Ranger shows preview of images, but when I go to another file, part of old image remains on window. To avoid this it's needed to change active window and then to return to konsole. May be, it's not supposed to be used on konsole

**Comment by toonn** [comment]
This is a known problem with w3mimgdisplay on konsole and there's not much we can do about it. There's an issue on the backburner about implementing refreshing after every preview, only for affected terminals of course because it's hideously inefficient. You could try C-r to see if a reset clears the previous image in the meanwhile.

**Comment by hektr** [comment]
Thanks. So it's better to disable pic preview :) For pics viewing it's better to use sxiv. Just highlight pic file in ranger, press l/enter, see pic, press q to close sxiv. Simple and effective. 

For navigating between images you can use space key and g key(to go at the very first pic) inside sxiv.

Besides, you can also see image in full-screen mode just by pressing f key inside sxiv. You can also adjust pic wide to screen/window wide just by pressing e (invert this by w). 

So, you can get all typical viewing actions just by pressing one key, it's very handy.

**Comment by toonn** [comment]
Sure, ranger's not an image viewer, it offers *preview*, some people like them, some people don't. You do you : )
