### ISSUE TITLE
[Q] Ranger wakes ZFS pool disks 

### ISSUE THREAD

**Issue by pascalwhoop** [ranger/ranger#1191]
Hi. This is a specific problem for me and I hope I'd find some ideas here.
I have my zfs pool mounted on ~/tank. When I open ranger, it opens the home folder and I guess accesses every folder within that directory. That wakes my sleeping drives. 
2 problems with that: 
- First, they don't need to wake unless I'm actually going to `tank`. 
- Second, ranger takes about 10 seconds to start because of this. Is there any way I can make ranger not call the OS on this directory or maybe have a different default open path?

**Comment by Vifon** [comment]
Try setting `set automatically_count_files false`, it might be the culprit. You may be interested in `set save_backtick_bookmark false` too, I used to have the same problem with my NAS because of it.

**Comment by pascalwhoop** [comment]
Good call. I think, if possible, the nicest way would be to have the default path be a different directory. Although I can imagine that being hard to implement as I start ranger using i3 shortcuts and they probably open a bash which by default is always in the home directory of the user.

**Comment by Vifon** [comment]
You can write a custom script doing `cd /` and then launching ranger though. No need to mix `bash_profile` into this.

**Comment by toonn** [comment]
Or a script that just calls `ranger /some/path`, no need to bring cd into this, right?

**Comment by Vifon** [comment]
I assumed he already tried that and I'm eager to believe ranger first loads its original cwd and only then chdirs. I didn't check it though.

**Comment by toonn** [comment]
Looking at the code, depending on the arguments it does so *twice* before loading the argument paths BUT only if you pass `--copy-config` or `--list-tagged-files`. Otherwise it creates an `FM` object, passing the argument paths. It does `import pwd` and calls `pwd.getpwuid()` but I assume that doesn't load the entire `PWD`.

I think we can't avoid the object initialization for `--copy-config` but maybe we can delay the `--list-tagged-files` check to after the real `FM`'s been created or at least check whether we already have an `fm` from the `--copy-config` check.

**Comment by pascalwhoop** [comment]
So for me personally, I believe the best approach is to start ranger from i3 using `r "/"` . But it seems like toonn found something that might be worth looking into on your side. So, from my side I'd close the issue because you helped me out but I leave that up to you to decide.

**Comment by Vifon** [comment]
If passing the start directory as an argument works, then it seems all is well. :)
