### ISSUE TITLE
Image previews render incorrectly on certain images

### ISSUE THREAD

**Issue by ettom** [ranger/ranger#1192]
#### Runtime Environment
Operating system and version: Xubuntu 16.04 with i3-gaps
Terminal emulator and version: URxvt 9.22
Python version: 2.7.12
Ranger version/commit: 1.9.1
Locale: LANG=en_US.UTF-8

#### Current Behavior

Stripes appear when rendering previewing images with w3m, sometimes the image doesn't render at all. This only seems to affect images with a very small file size, regardless of file type. It only happens when moving from a non-image to an image. 

#### Expected Behavior
Image previews render correctly.

#### Context
I am familiar with other issues regarding this problem. My issue seems to differ from all of those as most files render perfectly. I have tried the usual solutions e.g  `set draw_borders true` and `URxvt.depth: 24`.

#### Steps to reproduce
1. Try to view for example, [this](https://animalfactguide.com/wp-content/uploads/2013/01/iStock_000003074588XSmall.jpg) image with ranger.

**Comment by Vifon** [comment]
There isn't much we can do. The way w3m work is unreliable by design. I added a small delay in [my fork](https://github.com/vifon/ranger), please check if it helps. If it does, I'll add a configurable delay to the mainline. Since you're using urxvt, I encourage you to try the urxvt-specific preview method.

**Comment by ettom** [comment]
Seems to be working, thank you!
