### ISSUE TITLE
open_all_images not works for fbi

### ISSUE THREAD

**Issue by tkkcc** [ranger/ranger#1216]
#### Runtime Environment

- Operating system and version: archlinux 4.17.3-1
- Terminal emulator and version: linux console
- Python version: 3.6.5
- Ranger version/commit: 1.9.1
- Locale: en_US.UTF-8
#### rifle.conf
```
mime ^image, has feh, X, flag f = feh  -- "$@"
mime ^image, has fbi, =fbi "$@"
```

`set open_all_images true` works for `feh` but not for `fbi`

**Comment by toonn** [comment]
Ugh, who put this in there? `re.match(r'^(feh|sxiv|imv|pqiv) ', command)` Looking at you, hut -.- : p
Thanks for the bug report, this definitely seems fixable, not sure why the limitation is imposed like this.

**Comment by hut** [comment]
Because every image viewer needs special treatment. Since this feature opens all files, we need some way to specify which file to start at, and every image viewer implements this differently. From looking at the manual of `fbi`, I don't think there is an option to do specify a starting image like `feh --start-at $filename`, so I'm not sure we can support `open_all_images` with `fbi`. :(

**Comment by toonn** [comment]
Wouldn't we just have to sort the files right, cyclically, starting at the right file.

**Comment by hut** [comment]
Yeah, that could work. We'd have to verify that the image viewers support wrapping through the file list though, so that we're able to go back to the previous file.

**Comment by toonn** [comment]
Not sure that's required. Either we do A, B, C, always or we do abc, bca, cab depending on  the selected file. we choose one and users have to deal with it : ) We can hardly be expected to enable programs to do things they can't.

*Still* I think the regex is too limiting, there should be default behavior where we just pass all the files to the command, plenty of programs accept multiple files like that.
