### ISSUE TITLE
Ranger does not open current file(opens selected instead)

### ISSUE THREAD

**Issue by hektr** [ranger/ranger#1233]
If I select some file(s), and then want to open some another file, it opens only selected file, not the current(highlighted) file.

**Comment by Vifon** [comment]
This is the intended behavior though it would make sense to only operate on the selection when one of the selected files is focused. We'll think about it.

**Comment by toonn** [comment]
I'm not sure, I sometimes go through a directory marking things along the way, so I end up on an unmarked file most of the time but I do want to operate only on the marked files. Maybe not principle of *least* surprise but definitely principle of *most* useful ime.

**Comment by Aster89** [comment]
@toonn, when I scroll through image files in a directory and rely on their preview to decide whether I want to delete them or not, it often happens that I need to open the current image to make the decision (for instance because the preview is too big/small and I need to zoom in); in this situation I'd like <kbd>l</kbd> to open the current file.

Would it still be a bad idea to let <kbd>l</kbd> do what it does (open selected files) and change <kbd>→</kbd> to the other desired behavior (open current)?

**Comment by toonn** [comment]
Oh, btw, @Aster89, the zooming in part of what you do can mostly already be done with `i`, it opens the preview in the pager.

**Comment by Aster89** [comment]
@toonn , when I mentioned the zoom I was talking about image files. Yes, the map could be a good solution, but it's in your fork, not yet in the original, so I'd rather wait. Anyway I noticed the changes in the two commits you pushed to your fork are the same, aren't they?

**Comment by toonn** [comment]
Ah, yes. I amended the commit message because I noticed an inconsistency. You can read it if you click the ... after the first line of the commits above.

**Comment by Aster89** [comment]
Ouch! I saw the two distinct commit messages, but didn't understand it is a single commit.

**Comment by toonn** [comment]
Technically it's different commits because of the hash but yes : )

**Comment by Aster89** [comment]
I know this question is obviously ot, but I hope it's not a problem, since I could learn from this: haven't you rebased, squashed, and force-pushed to your own fork?

**Comment by toonn** [comment]
Don't think I rebased. Definitely didn't squash. Had to force-push because of the amend.
