### ISSUE TITLE
Stop StopIteration Issue Reports ; )

### ISSUE THREAD

**Issue by toonn** [ranger/ranger#1255]
We're getting many reports about a change in python 3.7:
```
RuntimeError: generator raised StopIteration
```
This has already been fixed in #1244.
There's a couple options:
  - Wait for the next release
  - Install the master branch (ranger-git in the AUR)
  - Downgrade to another version of python.

Thank you for your consideration. We <3 issue reports but please search both open *and* closed issues before opening a new one.

**Comment by bulletmark** [comment]
You say "Wait for the next release". Do you mean wait for the next release of ranger on Arch Linux? On Arch, ranger was updated 1.9.1-1 -> 1.9.1-2 on 06-Aug, are we waiting for a later release and will it happen soon?

**Comment by toonn** [comment]
That's an arch package release, don't know why that happened. I'm talking about a new version of ranger.

**Comment by bulletmark** [comment]
What I am saying is that this is a severe bug which is occurring in current ranger version 1.9.1-2 on Arch. Arch (and derivatives) is probably the only distro which has upgraded to python 3.7 and thus this bug is really only relevant to Arch users. I am asking when can we expect this bug to be fixed on Arch, i.e in hours, days, weeks, or months?

**Comment by toonn** [comment]
Well, it's already fixed. Imo if you want to run ranger on arch you should install ranger-git from the AUR. It's impossible to keep up with arch with our current release "schedule."

**Comment by bulletmark** [comment]
Do you mean by saying "Well, it's already fixed" that you believe it should be already fixed in the current Arch version 1.9.1-2? I find it still happens in that version.

I'm sorry, I just seem to be struggling to understand what you are meaning. Or, are you saying that using the formal ranger package on Arch is a waste of time (given such severe bugs can be left unaddressed in the formal version), and that we all should use the AUR package.

**Comment by toonn** [comment]
What I mean is that code has been contributed fixing the issue.
The number after the dash is a package version for arch, i.e. they changed something about the package, like who maintains it for arch or something. It is *not* a new version of ranger.

The ranger-git package installs the most recent commit on the master branch. Consider it our "rolling release."

What you call a "severe bug" is only a bug because the python developers decided to make it a bug. It's not a bug with any older python version.

What needs to happen to get a new ranger version into the arch repos is this:
 - We have to say "We're releasing version 1.9.2."
 - The maintainer for the arch package has to take note and modify the package to install the new version.

This may sound like a trivial amount of work, but it's not. There's also very little coordination between our team and package maintainers. That means it's not unusual for some time to expire between us releasing and the package being updated.

Arch is great for us because it gives us early warning on issues like this. As an Arch user you're stuck with software breaking from time to time. I'm working on a release, either be patient or go with the bleeding edge.

**Comment by bulletmark** [comment]
So, sorry, we get back to my question. Is it hours, days, weeks, or months before the next formal package release on Arch that fixes this problem? Just asking for a simple guesstimate in those rough terms.

**Comment by toonn** [comment]
Let's say days.

**Comment by bulletmark** [comment]
Thank you.
