### ISSUE TITLE
default terminal colorscheme is no longer inherited

### ISSUE THREAD

**Issue by sixpointzero** [ranger/ranger#1326]
#### Runtime Environment
- Operating system and version: Arch Linux
- Terminal emulator and version: Kitty 0.12.3
- Python version: 3.7.0
- Ranger version/commit: 1.9.2.8.g9454e9ff
- Locale: en_US.UTF-8

#### Current Behavior

This screenshot is from the latest (9454e9ff) git version of ranger.

![ranger_git](https://user-images.githubusercontent.com/19494538/46498402-fc383300-c83a-11e8-954c-a3eec5b06fc0.png)

#### Expected Behavior

This screenshot is from ranger 1.9.1 in the Arch repositories right now.

![ranger-1 9 1](https://user-images.githubusercontent.com/19494538/46498429-0d813f80-c83b-11e8-8cc7-267f17220169.png)

#### Steps to reproduce
1. Use a custom colorscheme in your terminal
2. Start ranger in the terminal (`$ kitty ranger`)
3. Notice the difference in behavior between master and 1.9.1

**Comment by toonn** [comment]
Which default colorscheme is no longer inherited, kitty's? And just to be sure you have `set colorscheme default` in your `rc.conf`, right? (Or no `rc.conf` at all.)

**Comment by soredake** [comment]
Same for me.

**Comment by toonn** [comment]
@soredake, are you using kitty too? And did you customize kitty's colors?

**Comment by sixpointzero** [comment]
> Which default colorscheme is no longer inherited, kitty's? And just to be sure you have `set colorscheme default` in your `rc.conf`, right? (Or no `rc.conf` at all.)

Yes, kitty's colorscheme isn't inherited versions >1.9.1

I haven't set that parameter in my rc.conf

**Comment by toonn** [comment]
Could either of you share your custom kitty colors? With the defaults it just works for me. I'm not on the latest kitty version though, maybe that matters?

**Comment by soredake** [comment]
@toonn kitty too
```
# black
color0   #000000
color8   #555753

# red
color1   #CC0000
color9   #EF2929

# green
color2   #4E9A06
color10  #8AE234

# yellow
color3   #C4A000
color11  #FCE94F

# blue
color4  #3465A4
color12 #729FCF

# magenta
color5   #75507B
color13  #AD7FA8

# cyan
color6   #06989A
color14  #34E2E2

# white
color7   #D3D7CF
color15  #EEEEEC
```

**Comment by soredake** [comment]
kitty 0.10.1 does not start sadly `kitty: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory`

**Comment by toonn** [comment]
Let's ping @kovidgoyal, is it possible kitty changed handling of colors, affecting curses applications, between versions 0.10.1 and 0.12.3?

**Comment by kovidgoyal** [comment]
No, there have been no changes to color handling in kitty in a long time. And here is a screenshot of kitty from master with atelier color scheme running ranger 1.9.1 on arch:

![screenshot_20181007_084754](https://user-images.githubusercontent.com/1308621/46577847-d31bcc00-ca0d-11e8-8ebd-77ddf2616003.png)

**Comment by sixpointzero** [comment]
So now we know that kitty isn't responsible for this change. I thought that maybe fish was responsible but it hasn't been updated since Dec 2017 and I tested kitty with bash but the colorscheme is still messed up in ranger versions >1.9.1. Everything works without any issues until ranger version 1.9.1 so it's probably a commit(s) in ranger after 1.9.1 that changed the behavior of how colorschemes are handled.

**Comment by toonn** [comment]
But I can't reproduce it...

**Comment by toonn** [comment]
Why would it work fine for the default colors though?

**Comment by kovidgoyal** [comment]
Just FYI you can use the --dump-commands flag to kitty to see the difference in what ranger is sending kitty between versions. This is a generally useful tool when debugging terminal programs. You can eit the dumped commands and replay them with --replay-commands -- a sort fo poor mans interactive debugger for terminal programs :)

And ti probably works for the default color scheme because its colors happen to match with whatever color overrides ranger is doing.

**Comment by toonn** [comment]
The default theme doesn't override any colors. It just uses the 8 basic colors. I'll give `--dump-commands` a shot though.

**Comment by kovidgoyal** [comment]
All color themes, whether default or not specify all 256 colors, in exactly the same way. In a terminal the 256 colors are implemented as a lookup table. Changeing the default colors, simply changes the entries in that lookup table.

**Comment by toonn** [comment]
I was referring to ranger's default colorscheme. It just uses the default colors for the terminal, I think those come from curses which probably just reads that table. So rangers colorscheme doesn't mess with the colors is my point. It just selects the right ones.

**Comment by toonn** [comment]
@kovidgoyal, this is a diff of two runs. One with my kitty colors (just changed black a tad to be visible on a black background) and the second with the atelier scheme. I can't make much sense of it. Could you explain which bits matter and what they mean?

```
--- scrollback1.txt	2018-10-07 15:57:13.000000000 +0200
+++ scrollback2.txt	2018-10-07 16:03:31.000000000 +0200
@@ -37,19 +37,17 @@
 screen_designate_charset 0 66
 select_graphic_rendition 0 
 select_graphic_rendition 38 2 85 85 85 
-draw d src/ranger/
-screen_cursor_back1 13
+draw at scrollback1.txt 
+screen_cursor_back1 19
 select_graphic_rendition 30 
 screen_designate_charset 0 66
 select_graphic_rendition 0 
 select_graphic_rendition 91 
 draw d
-select_graphic_rendition 38 2 85 85 85 
-draw  src/ranger/
-screen_cursor_back1 12
 select_graphic_rendition 30 
 screen_designate_charset 0 66
 select_graphic_rendition 0 
+screen_erase_in_line 0 0
 screen_backspace
 screen_backspace
 select_graphic_rendition 1 
@@ -503,7 +501,7 @@
 draw  
 select_graphic_rendition 39 
 select_graphic_rendition 49 
-draw yea~.txt
+draw scr~.txt
 screen_designate_charset 0 66
 select_graphic_rendition 0 
 draw  
@@ -511,7 +509,16 @@
 draw  
 select_graphic_rendition 92 
 draw Bobs.Burgers.S0~.srt 45.4 K 
-screen_cursor_position 23 11
+screen_carriage_return
+screen_linefeed
+select_graphic_rendition 91 
+draw  
+select_graphic_rendition 39 
+select_graphic_rendition 49 
+draw yea~.txt
+screen_designate_charset 0 66
+select_graphic_rendition 0 
+draw  
 select_graphic_rendition 91 
 draw  
 select_graphic_rendition 92
```

**Comment by kovidgoyal** [comment]
you need to look for select_graphic_rendition that is what controls colors. To understand the parameters, look for https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters

**Comment by kovidgoyal** [comment]
you sure that diff is complete? Because I dont see anything other than the SGR calls that could possible affect colors. But its easy to test, just replay the commands using --replay-commands merging the diff  piece by piece until you know which pice causes the issue.

**Comment by toonn** [comment]
And how do I check the result of the replay? Without starting ranger that is.

**Comment by kovidgoyal** [comment]
Simply run 

kitty --replay-commands file.cmds


inside a new kitty terminal.

**Comment by toonn** [comment]
I get the same result with both traces. I think I still don't understand.

**Comment by Vieler** [comment]
I get the same behaviour, and I can reproduce it with the following steps:

1. Open new terminal window
2. Open ranger, shows correct color scheme
3. Open a PDF file with zathura, color scheme is still correct
4. Open a PDF with evince (using `:open_with evince`), ranger goes to background (? I'm not sure, but as long as I keep evince open, the terminal window in which ranger was running shows my prompt instead)
5. Close evince, ranger resumes with wrong colors (everything is various shades of gray instead of solarized)

To recover the correct color scheme, I have to close the terminal and open a new window. But the old terminal window, in any case, retains the correct color scheme.
**System info**

- Arch Linux (with i3wm)
- GNOME Terminal 3.30.1
- Python 3.7.0
- Ranger (master) 1.9.1

**Comment by kovidgoyal** [comment]
@toon attach your two traces and I will take a look (use the --dump-bytes option to generate them, though rather than --dump-commands). And try to create them with minimal extraneous activity.

@Vieler you can always manually reset colors in a running kitty instance. It's in the kitty FAQ

**Comment by toonn** [comment]
@kovidgoyal, @Vieler seems to be running gnome-terminal, not kitty.

Here's how I created the dumps: `kitty --dump-bytes=scheme.dumpbytes -d ~/src/ranger ./ranger.py .` where scheme is either my own colors (defaults except for tweaked black) or the atelier scheme from above. Both times I quit the spawned kitty with ^C in the window where I ran the command and I did nothing like moving around in ranger. All I did between the runs was open the kitty preferences and change the theme then quit and restart kitty.app.
With my colors ranger looks like I'd expect it to. With the atelier scheme everything's grey. (Had to change the extension to .txt because github wouldn't allow me to upload the files otherwise.)
[mycolors.txt](https://github.com/ranger/ranger/files/2458149/mycolors.txt)
[atelier.txt](https://github.com/ranger/ranger/files/2458150/atelier.txt)

**Comment by kovidgoyal** [comment]
So I took a quick look, and on my system I get colors with atelier.txt as well. Slightly different colors, but not gray:
![screenshot_20181010_094228](https://user-images.githubusercontent.com/1308621/46712867-d1057780-cc70-11e8-8cb3-27d86e279dfe.png)

**Comment by Vieler** [comment]
I just wanted to add, after my first post, that my colors turn gray also when I open the keybindings help page (with `?k`) and then close it. So then I actually checked, and I lose my (initially correct) colors when I just start ranger, put it in background (`Ctrl-z`) and then hit `fg`. When it comes up again, it's gray.

But it seems like that for you guys the problem arises at startup, in my case it's only when I "leave" ranger and then come back.

**Comment by toonn** [comment]
@Vieler, yes it sounds like you have a different issue. It's possible understanding this one will lead to understanding yours but maybe open another issue anyway.

@kovidgoyal, that's very weird. I've bisected the problem to 60b566. This is the patch where we introduced bright in addition to bold. Any idea why adding 8 to the color's index would make everything end up in the same grey? Except for red, which ends up being black. (Also, I updated my kitty and it seems like exiting from the last open terminal doesn't quit kitty anymore, is there a setting I can change to get that behavior back?)

**Comment by kovidgoyal** [comment]
Sure there is a setting in kitty.conf, something like macos_quit_when_last_window closed or some such https://sw.kovidgoyal.net/kitty/conf.html

different terminals treat bold differently. Some will cause bold to use the "bright" variant, some will cause it to render with an actual bold font. some have a setting to toggle between the two. 

In kitty bold is always bold font, never bright. To use bright colors, you have to use the so called aixterm or bright color codes. See https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters  the section on colors.

I'm not a curses user, but you should check what actual SGR codes are being emitted, presumably something is not as it should be.

**Comment by kovidgoyal** [comment]
I'm guessing the problem is that in the atelier color scheme the bright color variants for 2,3, 4, and 5 are shades of gray. The bug in ranger is that it is sometimes using the non-bright variants and sometimes the bright variants. When it uses the non bright variants things are fine, when it uses thebright variants they are not

**Comment by toonn** [comment]
When it uses bright and when it does not is entirely up to the colorschemes and is intentional. So, @sixpointzero, I'm sorry to say the problem is with your theme. It'd be rather easy to change back to the way it was before though. Just copy the [old `default.py`](https://github.com/ranger/ranger/blob/v1.9.1/ranger/colorschemes/default.py) into `~/.config/ranger/colorschemes`, you could rename it if you want but you'd have to change your theme in `rc.conf` to the same name of course. Or you can always change to still other themes, create your own.

@soredake, with your colors I don't get the grayed out "issue" so I'm not sure what's going wrong for you? The colors should be brighter in 1.9.2 but that's just to get kitty in line with the appearance in other terminals. If you don't like it, I suggest the same solution given above.

@Vieler, your problem sounds like an actual issue. Does this happen for you in any other curses programs? Irssi, Vifm, something else?

**Comment by sixpointzero** [comment]
@toonn I'll try to use a different theme and report back.

**Comment by sixpointzero** [comment]
It looks like I somehow messed up the colorscheme earlier but ranger worked fine with the messed up version until 1.9.1. I modified the colors a bit to make the Atelier Cave colorscheme as follows and everything looks as expected.

```
#### atelier-cave dark colorscheme
# base00
background                #19171C
# base05
foreground                #8B8792
# base02
selection_background      #585260
# base05
selection_foreground      #8B8792
# base09
url_color                 #AA573C
# base05
cursor                    #8B8792

## black/grey - base01 and base03
color0                    #26232A
color8                    #655F6D
## red - base08 and base0F
color1                    #BE4678
color9                    #BF40BF
# green - base0B
color2                    #2A9292
color10                   #2A9292
# yellow/orange/brown - base0A and base09
color3                    #A06E3B
color11                   #AA573C
# blue - base0C
color4                    #398BC6
color12                   #398BC6
# magenta - base0E
color5                    #955AE7
color13                   #955AE7
# cyan - base0D
color6                    #576DDB
color14                   #576DDB
# white/silver - base05 and base04
color7                    #8B8792
color15                   #7E7887

# base08
active_tab_foreground     #BE4678
# base01
active_tab_background     #26232A
# base04
inactive_tab_foreground   #7E7887
# base01
inactive_tab_background   #26232A
```

@tonttu I'm closing this issue for now.
