### ISSUE TITLE
(flag to..) make scout filter relative path (to use with :flat)

### ISSUE THREAD

**Issue by eMPee584** [ranger/ranger#1441]
Currently, when in flat view, there is no way to filter by path (or is there?).. Use scenario:
1) go to /etc
2) filter `cron`
3) set :flat 1
now only files with `cron` in name are shown; instead, it would be nice if filter would match against the path and all files within the `cron.*` folders were listed (possibly with the introduction of another flag, or not).

**Comment by toonn** [comment]
Aha, good report about `:filter`, it just so happens that we've recently added something that's supposed to replace the filter command. It's called `:filter_stack` and it's in 1.9.2. And according to a very short test it behaves the way you'd want it to. So you'd apply the filter with `.ncron` instead of `zfcron` (literal keypresses, not `:commands`).

**Comment by eMPee584** [comment]
ah thanks @toonn, that was a swift solution to my itch even! didn't dive deeper into what it can do, but thanks to your awesome two-character-walk-through, I managed to apply it for this simple case. 👍😎

**Comment by eMPee584** [comment]
so coming back to this, what i miss from the `scout` command is
```
 scout [-flags...] [--] pattern
   Swiss army knife command for searching, traveling and filtering files.
 
   Flags:
    -g    Interpret pattern as a glob pattern
    -i    Ignore the letter case of the files
    -s    Smart case; like -i unless pattern contains upper case letters
    -t    Apply filter and search pattern as you type
```
with the case-insensitivity being of highest value right now :rofl:

**Comment by toonn** [comment]
That would be good as a seperate issue, like a @Vifon todo list basically : D
`-g` is lowest priority imo since it already supports regex the added benefit of globs is low. However, it's probably also very easy to add a `.g`.

`-i` is already possible thanks to an obscure python `re` feature, for example `(?i)This iS nOw A CASE insensitive PaTtErN`.

`-s` this is an important addition, since it's not very user friendly to have to pass `(?i)` but only *if* you want a case insensitive match, though I think the inline flag can be anywhere in the pattern, so you can literally decide at the end whether you want case insensitivity or not.

`-t` is the highest priority imo. It brings a much nicer UX.

And maybe we should look into merging the filter_stack and scout somehow? All of this would be trivial if you could do `.s` to add a scout filter to the stack.
