### ISSUE TITLE
Could not start ranger

### ISSUE THREAD

**Issue by btstw** [ranger/ranger#1455]
#### Runtime Environment

- Operating system and version: 
fedora24
- Terminal emulator and version: 
- Python version: 
python2.7.13
- Ranger version/commit: 
master
- Locale: 
english

#### Current Behavior
start ranger
showing error
```
Traceback (most recent call last):
  File "/usr/local/bin/ranger", line 35, in <module>
    import ranger  # NOQA pylint: disable=import-self,wrong-import-position
ImportError: No module named ranger
```

#### Expected Behavior
start ranger correctly

#### Steps to reproduce
1. make install
2. start ranger
3. showing error

#### Traceback
```
[install_log.txt](https://github.com/ranger/ranger/files/2798583/install_log.txt)

```

**Comment by btstw** [comment]
turns out ranger module install in /usr/local/lib/python2.7/site-packages but sys,path didn't include it.
so I add "export PYTHONPATH=/usr/local/lib/python2.7/site-packages" in my bashrc and it work now.

**Comment by toonn** [comment]
Hmm, not sure I recommend adding site-packages to your `PATH`. The default prefix for ranger is `/usr/local` so check whether `/usr/local/bin/ranger` exists and add `/usr/local/bin` to your `PATH` instead. Ah, indeed your install log points to `/usr/local/bin`. If you'd rather have it installed elsewhere you should be able to run `env PREFIX=/usr/bin make install` for example.

**Comment by snapdeus** [comment]
I experienced this issue installing in Cygwin.  Adding "export PYTHONPATH=/usr/local/lib/python2.7/site-packages" to my PATH did work.

Still looking for better solution.

**Comment by toonn** [comment]
@snapdeus, did you try my suggested solution, i.e., specifying a `PREFIX` for `make install`?

**Comment by snapdeus** [comment]
@toonn  Well, I have attempted this.  I did not get it to work unfortunately.

Full disclosure: I'm a noob and I don't think I properly uninstalled ranger in cygwin before issuing "env PREFIX=/usr/bin make install"  - and I can't find a way to properly uninstall it at the moment. 

At one point it seemed to install ranger in /usr/bin/bin which was not what I wanted.

Since I'm not sure on how to completely remove the installation of ranger from cygwin, I'm not sure how to proceed other than by reinstalling cygwin from scratch (again).  ah, such is life...

**Comment by snapdeus** [comment]
@toonn 

Success!  

Thank you. I found a dirty method of uninstalling ranger from cygwin (using windows file explorer...)

**I ended up needing to issue command: env PREFIX=/usr make install  and then it installed to my /usr/bin directory** (instead of /usr/bin/bin)

ranger now works in cygwin without having to add python package to PATH!

**Comment by toonn** [comment]
Ah, yes, sorry for the confusion. `Prefix` is normally `/usr/local` so you should indeed not add the `/bin`.

**Comment by CH-YYK** [comment]
Seems that `ranger` only support `python2.x`. This could be verified when a `python2.7` were launched and `import ranger` would work. I edited the shebang at the top line of ranger script which can be opened by the path of `ranger` from `python` to `python2.7`. Then it will search the package list of `python2.x`

**Comment by toonn** [comment]
That's not at all right. Ranger supports python 2.6+ AND 3.6+.

**Comment by sephid86** [comment]
If you use AUR, A clean build might be the way to go.
