### ISSUE TITLE
Map number keys

### ISSUE THREAD

**Issue by petobens** [ranger/ranger#1470]
Hi! Since one can do things like `3j` to move three lines down I thought that I could aIso add the following maps to my config file:
```
map u cd ..
map 2u cd ../..
map 3u cd ../../..
map 4u cd ../../../..
```
however only `u` (i.e the one without a preceding number) works as expected.  I found https://github.com/ranger/ranger/issues/931 asking basically the same but it was closed without explanation.

Thanks in advance!

**Comment by toonn** [comment]
I think that issue was just asking about how to map the number keys, i.e. have `2` toggle a mark or something.

What you're asking for is slightly different. Numbers always register as multipliers actually but only certain commands now what to do with them.
For example, if you'd use `map u move left=1` that'd have the same functionality except you can now do `4u` to move up 4 levels because move *does* understand the multiplier.

Keep in mind `h` already does this and `u`'s pretty useful to undo all kinds of things, like marking.

**Comment by petobens** [comment]
`move left=1` does the trick. Thanks!

**Comment by Bellavene** [comment]
`map <allow_quantifiers> false`
This will allow you to map numbers.
