### ISSUE TITLE
Regular releases

### ISSUE THREAD

**Issue by rightaway** [ranger/ranger#1521]
There have been many great features added since the last release almost 7 months ago and it would be nice to have it able to be packaged in official distributions which can only happen after a release.

I see the maintainers have added a useful document https://github.com/ranger/ranger/blob/master/doc/howto-publish-a-release.md about how to publish a release. I'm sure many people even me would be happy to take care of that process so that we could have new releases regularly.

**Comment by toonn** [comment]
Guess I stared myself blind on all the remaining issues. I'll cut a release in the near future.

**Comment by toonn** [comment]
It'd actually help if you listed the features you want in the release : )

**Comment by rightaway** [comment]
There have been many great features I've been watching the progress of over the last several months in `master` branch with interest, so releasing from that would be the best. :)

**Comment by aouerfelli** [comment]
If you're looking for anything specific, ueberzug image previews would be really nice to have in the release.

**Comment by toonn** [comment]
We always cut releases from master. @rightaway it'd still save a ton of work if you could list all the features. That's actually one of the most tedious parts of cutting a release, going through months of commits to figure out what to put in the changelog and check whether it's all been documented.

**Comment by alexanderjeurissen** [comment]
> We always cut releases from master. @rightaway it'd still save a ton of work if you could list all the features. That's actually one of the most tedious parts of cutting a release, going through months of commits to figure out what to put in the changelog and check whether it's all been documented.

I think this is the whole point of this issue, and the reason why continues deployment / releases are a best practice. The situation this project is currently in is a vicious circle where it's painful to do a release and as a result releases are done less and less frequent.

One thing that has worked for me in the past is automating the generation of the CHANGELOG file by just transforming the `git log` output in a human readable format. This does require that you squash commits before merging PR's however.

**Comment by toonn** [comment]
Mature software doesn't need frequent releases. Ranger's pretty stable. There's a userbase that wants the latest and greatest features and they just install ranger from the master branch (especially on arch) and that helps us a lot because it provides beta testing as it were.

Repeating the OP in saying there's a problem isn't very useful. I even responded to their offer to help with a suggestion of something they, or anyone really, could do that is fairly easy but time consuming and tedious and therefore something that makes us not look forward to doing releases. So far only @aouerfelli came through with something they're looking forward to. Mind you the ueberzug previews probably wouldn't have gone in earlier releases because it just hasn't been thoroughly tested yet, not enough people are using it. So we'll put it in the release, get more people using it and risk it being buggy.

From our POV you either use releases and we do our best to make sure they're stable and fairly bug free, or you run with master, our "rolling release", and risk things breaking. It's a git repository though so you can always roll back. We do our best to keep master 

We have precious little time to work on ranger. Asking us to spend that time doing frequent releases or improving our release process is simply counterproductive at this point. I've been working on ranger almost daily recently getting ready for the next release, it's not like we're ignoring OP's request.

**Comment by rightaway** [comment]
I actually do use it from master since a few days before creating this issue as I wanted to get the latest and greatest. But I created this issue anyway just because I love using ranger and thought others (I assume the majority of ranger users use it from their OS package manager like I used to) could benefit as much as I do from ranger and the quick speed at which you've been adding improvements. Just created it out of enthusiasm for ranger not because I'm waiting to upgrade personally anymore.

About release notes one thing I've seen projects do is add `(breaking)` or `(feature)` to git commit logs so that when it's time to do release notes all these issues are already identified and only those lines are added instead of all of them. Could also do `(bugfix)` but that's not totally necessary for release notes depending on the project. If that's something that might help for future commits then maybe for this one release notes could just be kept to the few most important points so that you don't need to go through everything?

**Comment by toonn** [comment]
I was only complaining about the repeated comments about how big of a *problem* our release schedule is, combined with a lack of extending a helping hand.

Marking commits for the changelog isn't necessary. Almost every significant change has a merge commit, they're easy to filter out. What's hard (tedious mostly) is identifying what exactly changed and how to describe it in one line.

This isn't the most significant part of doing a release btw. It's *just* a part that should be easy enough for pretty much anyone to help out with and save us a non-trivial amount of work.

Another thing that could *really* speed up a release is thorough testing of PRs, identify bugs before they get into master.

**Comment by friederbluemle** [comment]
There's been quite some activity in this repo recently. Thanks for all the hard work @toonn :pray: 
Looking forward to a new release in the (hopefully) near future :)

**Comment by toonn** [comment]
Yeah, me too. There's only a couple more issues/PRs with the bug label in the v1.9.4 milestone.
