### ISSUE TITLE
tagging is broken

### ISSUE THREAD

**Issue by Boruch-Baum** [ranger/ranger#1558]
In debian, with ranger version 1.9.2, using python 3.7.3:

1) tags other than the default "*" do NOT appear to the left of a file name. Reproduce by opening ranger, and keying `t` on a file, then `"a` on another file, then `"b` on a third file.

2) Attempting to assign a third tag results in an error message "no bookmark defined" for the tag. Reproduce by performing the steps in item #1 above, and then on a fourth file keying `"c`.

SOLUTION: This seems to be a problem in the default file `rc.conf`. On line ~368:
```
map "<any>  tag_toggle tag=%any  #"
```
If one removes the trailing `#"`, then ranger performs as advertised. My gues is that those characters were added for cosmetic reasons for editors that highlight syntax based upon matching quotation marks. If that's correct, then a work-around would be:
```
map "<any>  tag_toggle tag=%any
#" Ignore this line but do not remove it

**Comment by toonn** [comment]
That's the most likely reason. It's no longer in the default `rc.conf` though. And I'm *not* a fan of having broken editor workarounds in there so I'm gonna leave it be.

Since you're a pretty active user re bug reporting, consider running the master version of ranger. We try not to break it. Means you'll get fixes and new features a lot quicker and we'll get some bugs reported *before* release : )
