### ISSUE TITLE
Smarter `pp` paste for existing files

### ISSUE THREAD

**Issue by laktak** [ranger/ranger#1616]
When you paste a file that already exists (e.g. `yy` followed by `pp`), ranger will append a `_` to the name.

At the moment this breaks the file extension (e.g. `foo.txt` becomes `foo.txt_`).

Could this be changed to insert the `_` before the extension? Would you accept a PR for this?

**Comment by toonn** [comment]
I don't like it. Extensions are *really* hard to guess and it's a lot less obvious that something's amiss. I'd rather fail harder, faster. You *could* write rifle rules so you can still open such files easily.

*If* we changed it we'd change it to a prefix, that way you don't have to worry about extensions.
A problem either way is that it's not clear *which* are the renamed files after such a paste if there's files with multiple affixes afterwards. So maybe asking for confirmation for each file would be better?

Another solution would be to hash all the clashing files, then create a directory containing that hash, if it already exists forget about those files, otherwise put them in there. Ugly? Yes but also less ambiguous. Still not ideal if you paste tons of clashing files though, "Which hashed directory did the last paste go into?"

**Comment by laktak** [comment]
Hmm, I would argue that there is nothing amiss. By using `pp` I expect ranger to rename conflicting files instead of overwriting them with `po`.

What do you mean with extensions being hard to guess. Do you mean long extensions like `.tar.gz`? But even only taking the short extension would improve the situation (so you would get `foo_.md` instead of `foo.md_`). A prefix (`_foo.md`) is OK but it would also move the file away from the original in the list.

**Comment by toonn** [comment]
I know, it'd group all the conflicting files. A half-assed solution wouldn't be an improvement imo. And dots don't always separate extensions `Masterpiece.2019.07` would be a perfectly valid name for a text file.
The fact that the suffix "breaks" the extension is a feature, not a bug. It's how you know something's amiss.

**Comment by laktak** [comment]
OK, I see your point. I still don't like this feature.

**Comment by toonn** [comment]
I'm reopening this because I could see prefix v. suffix as a setting or better yet a flag passed to the paste function. (Maybe a function argument instead so you could pass a "Insert _ before best guess at extension" function even.)

**Comment by laktak** [comment]
The path is generated here: https://github.com/ranger/ranger/blob/master/ranger/ext/shutil_generatorized.py#L106-L119

I've modified it so it uses Python's splitext function to get to the extension of the file:

```
def get_safe_path(dst, keep_ext=False):
    if not os.path.exists(dst):
        return dst

    if keep_ext:
        dst_name, dst_ext = os.path.splitext(dst)
    else:
        dst_name, dst_ext = (dst, '')

    if not dst_name.endswith(APPENDIX):
        dst_name += APPENDIX
        if not os.path.exists(dst_name + dst_ext):
            return dst_name + dst_ext
    n = 0
    test_dst = dst_name + str(n)
    while os.path.exists(test_dst + dst_ext):
        n += 1
        test_dst = dst_name + str(n)

    return test_dst + dst_ext
```

The function is used in `copy2`, `copytree` and `move`. These are all called from [`CopyLoader`](https://github.com/ranger/ranger/blob/master/ranger/core/loader.py#L51) where its `overwrite` flag is passed along. Finally, `CopyLoader` is called from the paste action:

```
def paste(self, overwrite=False, append=False, dest=None):
```

So you want to add a new arg there? Would it be simpler to deprecate overwrite and replace it with an enum (overwrite/rename_dup/rename_dup_ext). The default should stay the same?

**Comment by toonn** [comment]
What I'd do is replace the calls to `get_safe_path` with an argument that defaults to it, `user_safe_path=get_safe_path` and  then call `user_safe_path(somePath)` instead.

**Comment by laktak** [comment]
@toonn please take a look at the PR.

**Comment by laktak** [comment]
Closing as this was merged :+1:

**Comment by toonn** [comment]
Thanks : )
