### ISSUE TITLE
Preview blacklist/whitelist in settings / callback

### ISSUE THREAD

**Issue by blueyed** [ranger/ranger#167]
PREVIEW_BLACKLIST and PREVIEW_WHITELIST from ranger/container/file.py should be moved into settings.

doc/HACKING mentions that it's a common thing to change, and it feels dirty to change the source for this.

(In my case it's a directory with symlinks that are on a remote system, managed via autofs - and I do not want them to be accessed when moving across the parent dir)

I think it might be even better to have a method of providing a callback for `file.has_preview`.
The preview blacklist has the drawback of only matching against the basename, and not the full path.
A callback would get more information (e.g. the whole path) and could decide if a preview should be provided based on additional conditions.

The callback should be allowed to not only look at files, but also directories, i.e. it should be added to https://github.com/hut/ranger/blob/master/ranger/gui/widgets/browsercolumn.py#L112-122.

_Edit:_ for my use case the hook would be needed in `_draw_directory` (https://github.com/hut/ranger/blob/master/ranger/gui/widgets/browsercolumn.py#L202-204), because I want to skip drawing the directory (if `level` is > 0).

**Comment by blueyed** [comment]
@hut 
I would appreciate feedback on how this should get implemented.

**Comment by hut** [comment]
It would be fairly easy to write a plugin that overrides the regular rexpressions used in the source.
```py
import re, ranger.container.file
ranger.container.file.PREVIEW_BLACKLIST = re.compile(r"...")
ranger.container.file.PREVIEW_WHITELIST = re.compile(r"...")
```
Put that file in `~/.config/ranger/plugins/` and you're good to go. Is this an acceptable solution?

**Comment by blueyed** [comment]
No, because the preview blacklist has the drawback of only matching against the basename, and not the full path.

I think a callback would be better, and it should make it possible to skip `stat`ing files altogether in this case (because that can be extremely slow, when the remote system is hibernated and needs to wake up).

**Comment by hut** [comment]
Oh, I overlooked that in your original post.

If `stat`ing is the problem, then you should be aware that ranger stats files at various other places in the code. Some I can think of are the status bar and the check whether the current column needs to be redrawn which is done in every iteration.

On topic: How about directly overwriting ranger.container.file.File.has_preview in a plugin? Or ranger.gui.widgets.browsercolumn.BrowserColumn.has_preview? I guess the downside of that is the code may change and then plugins will break. So some separate callback function in ranger.api.__init__ may be more useful.

But regarding your underlying problem, the way I solve this issue is with lines like this:
```
setlocal path=/media/remotemount/.* preview_directories False
setlocal path=/media/remotemount/.* preview_files False
```

**Comment by nfnty** [comment]
As mentioned by @hut, just use `setlocal`.
