### ISSUE TITLE
[Enhancement] Put items into trash

### ISSUE THREAD

**Issue by Hocuri** [ranger/ranger#1699]
#### Runtime Environment

Operating system and version: Manjaro
ranger version: ranger-master 1.9.2
Python version: 3.7.4 (default, Jul 16 2019, 07:12:58) [GCC 9.1.0]
Locale: en_US.UTF-8

#### Current Behavior

On press of F8, items are deleted after confirmation

#### Expected Behavior

On press of F8, put item into trash without asking

#### Context
I am much faster with Ranger than with other file managers but one feature it lacks is trash support, which is very sad because this makes using Ranger a little dangerous (because I could accidentally delete a file) and annoying (because I have to confirm deletion, when I delete a folder even twice)

#### Possible Solutions

Integrate trash-cli

**Comment by Vifon** [comment]
I think it could be resolved as a user's configuration:

```
map <F8> shell trash-rm %s
```

I don't think including it in the defaults would be a good idea, because of the added dependency among other reasons. But I am open to discussing it.

**Comment by toonn** [comment]
I guess there wouldn't be harm in adding a rule for `trash-rm` to `rifle.conf`, not that that would be incredibly comfortable to use. But could be used in a mapping. And if we use a "delete" label maybe we can even have `:delete` use `rifle delete/trash/whatever` by default?

**Comment by davoudarsalani** [comment]
I use this map to use a script I have made to send selected items to trash directory:
map <S-delete> shell $HOME/scripts/trash %s

**Comment by thiswillbeyourgithub** [comment]
Hi, sorry to reopen this but I spend quite some time fine tuning a command to trash and untrash files. As it turns out my version on ubuntu was wayy outdated (1.8 something) so contained no mention of the trash function.

Anyway my keybinding is still okay for me so I'll keep using it, but I thought some people might benefit from these poorly written lines :

```
map DD shell mv -i %s /home/$USER/.local/share/Trash/files/ && echo "trashed %s        from_dir $(pwd)" >> /home/$USER/.config/ranger/trash_history 

map uD shell fileToRestore=$(cat /home/$USER/.config/ranger/trash_history | grep "^trashed" | tail -n 1 | cut -c10- | awk -F"from_dir " '{print $1}' | rev | cut -c10- | rev) && mv -i /home/$USER/.local/share/Trash/files/$fileToRestore $fileToRestore && echo "         untrashed $(pwd)/$fileToRestore" >> /home/$USER/.config/ranger/trash_history && unset $fileToRestore
```

* Just type `DD` to move a file to the trash and `uD` to undo the last trashing.
* You have to reload via `R` after restoring to refresh the ui.
* mv is with the option -i to be interactive in case there is already some file present. 
* You can find a trashing history in ~/.config/ranger/trash_history. Nothing will happen in case of `permission denied`.

May I suggest that  this could be mentionned in the common-change section and should replace the command in the archwiki page that talks about trash

also related to #10

**Comment by toonn** [comment]
Feel free to contribute to either wiki, they're open to the community.
