### ISSUE TITLE
Gifs not opening properly

### ISSUE THREAD

**Issue by deracinator** [ranger/ranger#1814]
#### Runtime Environment

- Operating system and version: Linux 5.4.13-arch1-1 SMP PREEMPT Fri, 17 Jan 2020 23:09:54 +0000 x86_64 GNU/Linux
- Terminal emulator and version:  termite v15
- Python version: Python version: 3.8.1 (default, Jan  8 2020, 23:09:20) [GCC 9.2.0]
- Ranger version/commit: ranger 1.9.3
- Locale: System Locale: LANG=en_US.UTF-8

#### Current Behavior
Gifs are always opened with feh, what causes that just the first frame be displayed static in a new feh window.
#### Expected Behavior
Gifs being played, not just the static first frame

#### Context

I'm using ArchLinux and Termite on i3wm and ranger always uses feh to open gifs while it should not, since feh [is not(and will not be in the near future)](https://github.com/derf/feh/issues/308) able to play gifs.
#### Possible Solutions
The first possible solution that comes to my mind is treating gifs as videos if feh is the main/only image viewer, since almost any video player will not complain about playing gifs, I added a personal mime type myself to always treat gifs as videos on my system and mpv plays them awesomely, but I don't think that this solution will be the best one since probably many people have a fallback image viewer and maybe they want to use it instead of a video player.
So maybe removing gifs from the supported file types that rifle says that feh can handle should be the best solution.
#### Steps to reproduce
1. Dowload any gif file.
2. Make feh the only image viewer
3. Open the gif file from inside ranger

**Comment by toonn** [comment]
I don't think this is a problem that can be "solved."

Some people might prefer viewing gifs frame by frame, people who create gifs, for example.
Others may use image viewers that *do* animate gifs, so I agree that simply pretending gifs are videos isn't an ideal solution either. And I'm not sure how many video players actually support playing gifs.

So the only reasonable solution I see is to have people configure `rifle` to open gifs the way they prefer. (This solution is currently implemented : ))

**Comment by Deracinator** [comment]
Maybe you didn't understand what I've said, feh does not open to see "frame by frame", it **just** shows the first frame. Quoting feh's manual:

> SUPPORTED FORMATS
>      feh can open any format supported by imlib2, most notably jpeg, png, pnm, tiff, and bmp.  The gif format is also supported, but only for static images.  In case of animations, **only** the first frame will be shown.

I'm a person who make gifs on a daily basis, and I never needed to see only the first frame of any animated gif without being able play it or maybe not even play it, but just pass frame by frame, I can do that with mpv tho, frame by frame is a built-in keyboard action of mpv. That said, almost every player that was built based on mpv or libmpv(you can a see a comprehensive list [here](https://github.com/mpv-player/mpv/wiki/Applications-using-mpv) ) can play animated gifs, along with VLC and others.
But straightening to the topic, I don't think it is in any way useful to open an animated gif to just see the first frame of it, actually feh is not intended to handle images with more than one frame on it, as stated by feh's developer:

> feh is an image viewer and not a movie / gif player

**Comment by toonn** [comment]
That's all fine. But we can't distinguish animated from non-animated gifs afaik? So there's nothing to change without breaking something for someone. Mpv and vlc aren't the only video players, there's totem for one, quicktime, windows media player and whatever else. Animated gifs are a relic of the past, video codecs are far superior in suppressing gif-style animations. So for those few people that 1) use an image viewer that doesn't show a gif the way they want and 2) actually look at animated regularly, simply adding or changing a line in `rifle.conf` doesn't seem like too much to ask.

**Comment by Deracinator** [comment]
Well, I agree that gifs are old and that other filetypes are better for animations in most cases, but gifs are still vastly used in many occasions, and just to mention, AFAIK Windows Media Player and QuickTime support playing gifs natively, just Totem that I'm not sure...
But anyways, 

> "we can't distinguish animated from non-animated gifs afaik?"

Of course we can, and is actually pretty easy and simple, using ImageMagick from the command line for example you can issue the command `identify some-gif.gif` and it will show you all information about every frame inside a gif. Like this:
```
$ identify some-animated.gif
some-animated.gif[0] GIF 370x335 370x335+0+0 8-bit sRGB 256c 0.000u 0:00.002
some-animated.gif[1] GIF 370x335 370x335+0+0 8-bit sRGB 256c 0.010u 0:00.003
some-animated.gif[2] GIF 370x335 370x335+0+0 8-bit sRGB 256c 0.010u 0:00.003
some-animated.gif[3] GIF 370x335 370x335+0+0 8-bit sRGB 256c 0.010u 0:00.003
some-animated.gif[4] GIF 370x335 370x335+0+0 8-bit sRGB 256c 0.010u 0:00.003
some-animated.gif[5] GIF 370x335 370x335+0+0 8-bit sRGB 256c 0.010u 0:00.003
some-animated.gif[6] GIF 370x335 370x335+0+0 8-bit sRGB 256c 0.010u 0:00.003
some-animated.gif[7] GIF 370x335 370x335+0+0 8-bit sRGB 256c 0.010u 0:00.003
some-animated.gif[8] GIF 370x335 370x335+0+0 8-bit sRGB 256c 0.010u 0:00.003
some-animated.gif[9] GIF 370x335 370x335+0+0 8-bit sRGB 256c 0.010u 0:00.003
some-animated.gif[10] GIF 370x335 370x335+0+0 8-bit sRGB 256c 1.98435MiB 0.010u 0:00.002
```
or  when pointing to a single frame gif
```
$ identify some-static.gif
some-static.gif GIF 370x335 370x335+0+0 8-bit sRGB 256c 77466B 0.000u 0:00.000
```
and in python is still simple, in [this gist](https://gist.github.com/Deracinator/141729f389487b486e006f4d20d2e436) you can see a script that I created to be able to distinguish between single frames and non-single frames gifs using Wand

pointing to the same animated gif than before(10 frames):
```
$ ./is-animated.py some-animated.gif
Extracting frames information...
The gif is animated.
```
pointing to the same static one(1 frame):
```
./is-animated.py some-static.gif
Extracting frames information...
The gif is not animated.
```
or if the file is not a gif(even if the extension is .gif):
```
./is-animated.py not-a-gif.gif
This file is not a gif!
```
So maybe inserting a simple condition to evaluate if the gif has more than one frame or not, if it has, don't send it to feh, pretty simple right ?!


You were right when you said that is not that much to ask for the user to modify this configuration himself, but the only thing that would be better than modifying this by hand, is not needing to modify it, because 'my file manager is smart enough to handle even little annoying things like this one automatically'.
and just to clarify even more, I didn't opened this discussion with the intention to 'solve an issue' as you said, but with the intention to aggregate a useful (small) feature that would be appreciated by every person that uses ranger and feh(which is a very good minimal image viewer, don't get me wrong, just not for animated images) and stumble with this annoying "I can open your gif but IDC if it's animated or not, I will only show you the first frame and that's it" thing that feh does. I hope you understand what I'm saying.

**Comment by toonn** [comment]
I still don't see a nice way to handle this without special-casing both gifs and feh unfortunately. So the best I can do is make feh ignore all gifs.

**Comment by Deracinator** [comment]
LGTM, as you said from the few people like me that still open animated gifs regularly, it's very hard to find someone that want those animated images to be forcibly static by feh. So I think it's a good solution.
And to give you an idea for the future maybe, feh does not handle any other type of animated images too, like APNG or WebP... feh does the same thing that it does with animated gifs, it shows only the first frame and that's it... while APNG specially I think it would need a special case since it's a normal PNG image with other frames purposely hidden on it and the only way to figure out that the image is animated is to search for an acTL chunk in the file, this would demand a special case.
With WebP is easier than that, since the frames are not hidden is easier to detect if the image is animated or not. But maybe blacklisting WebP from feh would not be as good as blacklisting gifs too, because while gifs in the majority are animated, WebP images in the most part are not animated, but static.
So for now I think it's good to only handle the gifs case since it seems to be the simplest one, but I let you with this information so maybe in the future you can think about how to handle the other cases too somehow.
Thank you for your response to this !!!
