### ISSUE TITLE
Ueberzug previews sometimes don't display in the right column

### ISSUE THREAD

**Issue by catzybluphish** [ranger/ranger#1856]
#### Runtime Environment

- Operating system and version: Arch Linux
- Terminal emulator and version: rxvt-unicode 9.22
- Python version: 3.8.1
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
[Demonstration](https://files.catbox.moe/0qbmoa.mp4)
When I spawn a ranger window on the left (bspwm), the ueberzug preview will display on the right, as if the ranger window was on the right. However, when I do spawn a ranger window on the right, the preview displays in the proper position, and stays there if I move it.
#### Expected Behavior
To spawn in the proper position independent of where I spawn a ranger window.

#### Possible Solutions
I can switch back to w3m as it doesn't have this issue, but I'd prefer not to.
#### Steps to reproduce
1. install python-ueberzug from AUR
2. set preview_images_method ueberzug

Disabling transparency does not fix it.
#### One more thing
I have `ext xcf, X, flag f = gimp-2.10 -- "$@"` in my rifle.conf, but it doesn't open GIMP when I press right on an XCF file. Removing `-2.10` doesn't help. How can I resolve this?

**Comment by catzybluphish** [comment]
I'm not using ffmpegthumbnailer btw as I have it disabled. The issue is persistent on image files as well.

**Comment by toonn** [comment]
IIRC there's problems with that AUR package. There's a better one that has "git" in the name I believe. But the only officially supported package by @seebye is the PyPI package. Try installing one of those to confirm the issue first.

When the xcf file is highlighted does `r` list the gimp rule?

**Comment by seebye** [comment]
It looks like you're using the daemon mode of urxvt.. disable it.

**Comment by catzybluphish** [comment]
> When the xcf file is highlighted does `r` list the gimp rule?

@toonn Yes. It's definitely not a big deal for me to just open it from `r`, just thought I might've missed an option.


> It looks like you're using the daemon mode of urxvt.. Ueberzug requires terminal emulators to have only one window per process, so you need to disable the daemon mode.

@seebye I see that is the case. Disabling daemon mode fixes the issue. Is it possible to work ueberzug with the urxvt daemon, or is it not possible? If not, I'll have to switch back to w3m.

**Comment by seebye** [comment]
I don't plan to support daemon modes.  
Also I don't see an advantage of using it for an terminal emulator.  
It's not like these processes are really expensive or require a reduced latency of an ms or something like that.  
Strictly speaking determining the correct window is already a non decideable problem (easily provable by the theorem of rice) which can only be solved under specific conditions.  
So it will never work for every possible way of creating a program.  
There is a subset of the set of programs which creates a x11 window for which ueberzug is able to make a correct decision if your terminal emulator isn't in this subset  (e.g. because it uses a daemon mode) you're just out of luck.  
(w3m makes a correct decision for another subset of the problem which is why it works with it)

**Comment by toonn** [comment]
Re the rifle rule, did you add it low in `rifle.conf`? If it's not the first option in the `r` menu it won't be picked when you go right on a file.

**Comment by catzybluphish** [comment]
> Re the rifle rule, did you add it low in `rifle.conf`? If it's not the first option in the `r` menu it won't be picked when you go right on a file.

Thanks, that resolved the issue.
