### ISSUE TITLE
unable to copy file names

### ISSUE THREAD

**Issue by ghost** [ranger/ranger#1861]
#### Runtime Environment

- Operating system and version: Arch Linux
- Terminal emulator and version: Kitty 0.16.0 and QTerminal 0.14.1
- Python version: 3.8.1
- Ranger version/commit: 1.9.3 and the latest git version
- Locale: en_US.UTF-8
#### Current Behavior
before pressing trying to copy file name by pressing `y` and `n`
![before](https://user-images.githubusercontent.com/47925053/75623301-a225d380-5bce-11ea-9872-8e038161e6df.png)
#### Expected Behavior
after pressing `y` and `n`
![after](https://user-images.githubusercontent.com/47925053/75623305-abaf3b80-5bce-11ea-9902-16ac8035b289.png)
#### Context
I'm unable to use many shortcuts and I can't copy file names

**Comment by toonn** [comment]
Try moving your config out of the way, `rc.conf`, `commands.py` etc. and check if the problem persists.

**Comment by pointfourone** [comment]
@toonn I used `ranger -c` and the problem still happens.

**Comment by pointfourone** [comment]
nvm, I was able to fix the issue by removing wayland packages. I suspect the presence of wl-clipboard when using Xorg triggers this bug although I don't think this should be expected behavior.

https://github.com/ranger/ranger/pull/1719

**Comment by toonn** [comment]
Oh, crap. `wl-clipboard` takes precedence. We should try to find out whether we're running on Wayland and choose accordingly. Though I have no idea how this might interact with XWayland.

**Comment by kovidgoyal** [comment]
Just FYI, you should use OSC 52 rather than calling external programs. That way it will just work in all modern terminal emulators, over ssh as well. https://sw.kovidgoyal.net/kitty/protocol-extensions.html#pasting-to-clipboard

**Comment by toonn** [comment]
Thanks for the suggestion that sounds a lot more sensible!

**Comment by toonn** [comment]
@kovidgoyal, I'm finally looking into your suggestion. Is there a reference for these OSC control sequences and specifically OSC 52? My google-fu is failing me. I'm particularly interested in whether there's a way to detect if the terminal we're running in supports the control sequence?

About your recommendation of sending an invalid OSC 52 to reset Kitty's clipboard behavior. If I understand correctly, to copy an entire file to clipboard, we'd base64 encode it, send an invalid control then cut it up in chunks that fit control sequences? So in terminals that don't exhibit the same behavior we'd end up with just the last chunk copied? That doesn't sound great as a silent failure so maybe the behavior should be specific to Kitty?

**Comment by kovidgoyal** [comment]
On Thu, Jul 22, 2021 at 10:55:42AM -0700, toonn wrote:
> @kovidgoyal, I'm finally looking into your suggestion. Is there a reference for these OSC control sequences and specifically OSC 52? My google-fu is failing me. I'm particularly interested in whether there's a way to detect if the terminal we're running in supports the control sequence?

No there's no detection for OSC 52, but (famous last words) pretty much
all terminals that dont understand it should just ignore it with no ill
effects.

> 
> About your recommendation of sending an invalid OSC 52 to reset Kitty's clipboard behavior. If I understand correctly, to copy an entire file to clipboard, we'd base64 encode it, send an invalid control then cut it up in chunks that fit control sequences? So in terminals that don't exhibit the same behavior we'd end up with just the last chunk copied? That doesn't sound great as a silent failure so maybe the behavior should be specific to Kitty?

Most terminals will have some max size limit on escape codes, so if you
don't chunk it up, you will get silent incomplete or entirely dropped copies
anyway. 

What I would suggest doing is 

1) base64 encode. 
2) Send invalid escape code
3) Check the length of the encoded text, if it is less < 4000 bytes, send as unchunked. If it is > 4000
bytes and you detect kitty, chunk it up, otherwise send as single escape
code.

**Comment by kovidgoyal** [comment]
Actually you might want to hold off for a few days. I think I can add support for inifite length pastes in kitty without needing chunking. If I succeed then you dont need to bother with this at all.

**Comment by kovidgoyal** [comment]
And success: https://github.com/kovidgoyal/kitty/commit/8f214c51c092d79e90fea25ec2e5db117af0054b

**Comment by toonn** [comment]
@kovidgoyal, thank you, that sounds like it allows us to take a more uniform approach. IIUC this means all we need to do is base64 encode and then send the entire thing and terminals that have an upper limit will just truncate the contents, including Kitty if we go over 8 MB? So the invalid sequence to reset Kitty's clipboard handling is no longer necessary?

I'm still thinking about how to integrate this behavior. If we can't test for OSC 52 support or whether the control sequence results in success I guess the only option is to use it as a fallback in case wl-clipboard or xclip and xsel aren't present? Or do you see another alternative? I don't like simply dropping the utilities because that would break setups that work currently. If desirable a setting could be added to avoid the inefficiency of the utilities and only try the control sequence.

**Comment by kovidgoyal** [comment]
Yes, all you need to do is base64 and transmit. In kitty anything over 8MB will be silently ignored.

There are further wrinkles you should be aware of. 

1) If you exceed the maxsize for some terminals its possible they will print garbage to the screen (depending on how they handle overlarge escape codes). 

2) Since reading/writing to the clipboard is a security risk, many terminals make it user configurable whether OSC 52 is allowed or not. For instance in kitty there is a clipboard_control option, that defaults to allowing writes to clipboard but not reads from it. And to help, I have added the ability to query the status of this setting in kitty via the https://sw.kovidgoyal.net/kitty/kittens/query_terminal/ kitten. So you can run kitty +kitten query_terminal to check if it is allowed. (from the next kitty release).

So I suggest as a first step keep it as a user option and gather feedback for how it works in the wild among your userbase. If in practice the problems are not significant you can change the default for the option later.

**Comment by toonn** [comment]
@kovidgoyal, I don't think implementing it as a fallback in case the utilities aren't installed is ever harmful so I'm intending to do that. I did have one more question.
It's sometimes possible to copy things like images to the clipboard. I'm not sure how that works, I think the MIME type is somehow included in the data? Is this possible with OSC 52?

**Comment by kovidgoyal** [comment]
On Sat, Jul 24, 2021 at 11:33:29AM -0700, toonn wrote:
> @kovidgoyal, I don't think implementing it as a fallback in case the utilities aren't installed is ever harmful so I'm intending to do that. I did have one more question.

The advantage of OSC 52 is that it works over SSH, unlike the utilities.

> It's sometimes possible to copy things like images to the clipboard. I'm not sure how that works, I think the MIME type is somehow included in the data? Is this possible with OSC 52?

No, not with OSC 52. If its something you are interested in one
would need to design a new escape code for it, and it would be
kitty specific.

**Comment by kovidgoyal** [comment]
Just FTR that new escape code now exists: https://sw.kovidgoyal.net/kitty/clipboard/

allowing copying of all data types to the clipboard.
