### ISSUE TITLE
How to use "cd $var"?

### ISSUE THREAD

**Issue by zdmgmail** [ranger/ranger#1869]
$var is Environment variable
I can use:
	map et  shell nvim $timeDir/\`date "+%m"\`.md
But
	map gt cd $timedir
	shell cd $timedir
	not work

map et shell nvim $timeDir  also not work perfect

Is there a good way to solve it ?

**Comment by toonn** [comment]
`map gt cd $timeDir` wouldn't work, that's ranger's `:cd` command, it doesn't run in a shell so there are no environment variables.

`map gt shell cd $timeDir` works, but you're expecting it to do something it can't, the `cd` is executed in a subshell and in fact changes the subshell's PWD but then the subshell exits and nothing's changed in the parent shell. That's expected behavior. It's similar to how executing a script with the contents `cd $timeDir` won't change your PWD.

If you really want to do this you could try `map gt eval fm.cd(os.getenv('timeDir'))`.

**Comment by zdmgmail** [comment]
Perfect answer, thanks!
