### ISSUE TITLE
Background selected file name to heavy, can't read the name.

### ISSUE THREAD

**Issue by roachsinai** [ranger/ranger#1879]
#### Runtime Environment

- Operating system and version: Manjaro 19.0.2
- Terminal emulator and version: Konsole 19.12.3
- Python version: python 3.8.1
- Ranger version/commit: 1.9.3.4.gd8c363c9-1
- Locale: zh_CN.utf8

#### Current Behavior

![image](https://user-images.githubusercontent.com/9500049/76775564-7f0b3e80-67e0-11ea-8d7a-5f1f210600ba.png)

#### Expected Behavior

The text of ranger focus file readable.

#### Context

Find a way `export TERM=xterm`, to make it a little(literally, lol) readable! but not suit for all official colorscheme.

`default` a little readable:

![image](https://user-images.githubusercontent.com/9500049/76776910-5ab06180-67e2-11ea-8ff1-ad95b2d368b2.png)

`jungle` still can't read:

![image](https://user-images.githubusercontent.com/9500049/76778334-99471b80-67e4-11ea-8197-2054b2830877.png)

`snow` directory have same state with file:

![image](https://user-images.githubusercontent.com/9500049/76778456-d6aba900-67e4-11ea-98ce-c08c155d2d17.png)

I'm using Konsole Gruvbox dark colorscheme: https://github.com/morhetz/gruvbox-contrib/tree/master/konsole

**Comment by toonn** [comment]
I think the only solutions are to either change the offending colors in the ranger colorscheme, i.e., creating your own custom scheme. Or to change the offending colors in your terminal's theme.

Tbh, imo your terminal's theme isn't well designed, any two colors should have sufficient contrast otherwise all application designers would have to give up most of the available colors because some themes have bone-headed combinations.

**Comment by roachsinai** [comment]
Thanks for your suggestions. I'll try other colorschemes.
