### ISSUE TITLE
failed to preview PNG and SVG file, but JPG and PDF files are ok.

### ISSUE THREAD

**Issue by Boltzmachine** [ranger/ranger#2059]
#### Runtime Environment

- Operating system and version: Arch Linux
- Terminal emulator and version: st 0.8.4
- Python version: 3.8.3
- Ranger version/commit: 1.9.3
- Locale: en_US.utf8
- w3m

#### Current Behavior
When I preview png and svg file, the image just flashed and disappeared immediately. But jpg and png file are OK.

#### Expected Behavior
The picture should linger in the terminal

#### Context

View the svg and png.

#### Steps to reproduce
1.  open ranger
2.  focus on a png or svg file

#### Traceback

```
```

**Comment by toonn** [comment]
Svg would only be previewed if you altered `scope.sh` and you have the necessary dependencies installed.
For png, check if it works when running `ranger --clean`.

**Comment by Boltzmachine** [comment]
If I use ``ranger --clean``, all of the pictures will not show. in the terminal If I use uezburg, all of them work but PNG will not show its transparent background.

**Comment by toonn** [comment]
Transparency is up to the previewing method, ranger has nothing to do with that. Note that conversion steps in `scope.sh` might affect transparency.

When I said `ranger --clean` I should've added that you then need to manually set the preview method and enable previews after starting ranger.

If ueberzug works and w3m doesn't the problem is almost certainly your terminal just not being compatible enough with w3mimgdisplay. The w3m team only officially supports XTerm.

**Comment by Boltzmachine** [comment]
Ok. Maybe st is not compatible, thank you.
