### ISSUE TITLE
Resetting color scheme

### ISSUE THREAD

**Issue by salteax** [ranger/ranger#2147]
My ranger file manager is resetting color scheme to default after for example opening a folder i have no access to or opening a file with 'r'... what can i do to fix this? It also resets the color scheme of my terminal (allacritty)

**Comment by toonn** [comment]
Ranger does no such thing. Are you using pywall to set your theme?

**Comment by salteax** [comment]
> Ranger does no such thing. Are you using pywall to set your theme?

yes i am

**Comment by toonn** [comment]
The problem is in the way pywall sets themes. It doesn't actually affect the terminal's configuration, it just injects the proper escape codes. There's a previous issue about exactly this problem. Don't remember whether that's still open or whether it was resolved. "pywall" is probably a good search term.
