### ISSUE TITLE
Possibel to persistently hide some files?

### ISSUE THREAD

**Issue by introom** [ranger/ranger#2162]
On macos, the files .DS_Store and Icon? is annoying and I want to hide it forever, no matter if show_hidden is on or not.

A runtime approach would be :
filter -rpv (.DS_Store|Icon?)

But that command cannot be added to the rc.conf

**Comment by chu4ng** [comment]
filter_stack not work with ALL directories, only for thisdir. _I think._
May be good enhancement, but now you can add Icon-files and other files in "hidden_filter" optrion inside the rc.conf.

**Comment by toonn** [comment]
`filter_stack` is indeed local, there's a feature request for broader applicability here #1962, I'm closing this in favor of that issue.
Setting `hidden_filter` won't help in this case because that would show the `.DS_Store` file no matter whether hidden files are shown or hidden currently, which is the opposite of what OP wants.
