### ISSUE TITLE
Ranger has alignment/formatting issues when executing from external terminal

### ISSUE THREAD

**Issue by erichamers** [ranger/ranger#2180]
#### Runtime Environment

ranger version: ranger-master
Python version: 3.9.0
Locale: en_US.UTF-8
OS: Arch Linux
Window Manager: qtile 0.16.1

#### Current Behavior
When I open ranger from the terminal (Alacritty), it works fine just by typing `ranger`. But when I try to open in in a different terminal window, by doing `alacritty -e "ranger"`. Everything get's messed up, the alignment, the formatting.

#### Expected Behavior
Executing on the same terminal window or in a different one should yield the same result.

#### Context
I'm trying to set a keybinding in qtile to run ranger by using a keyboard shortcut, so I have to run it with `alacritty -e "ranger"`

#### Steps to reproduce
1. In alacritty, type `ranger`, see normal results.
2. Now type `alacritty -e "ranger"` and see everything messed up.

**Comment by toonn** [comment]
Could you comment on why you closed this? I wouldn't be surprised if there's kind of a race condition where ranger reads the window size, qtile changes the window size and SIGWINCH signals are sent but not caught by ranger.

**Comment by erichamers** [comment]
Hi @toonn , this problem is happening on qtile, I tested it on i3 and the problem goes away. Also another thing I found was that this happens if there is already another window opened in that group, if ranger is the first window to open, it works fine. But I figured this is more of a qtile problem than a ranger problem, no? Let me know if this is worth reopening or if you need more info on the issue.

**Comment by toonn** [comment]
Maybe the qtile developers can tell you why this happens? Like I said, I wouldn't be surprised if this is something we could improve.

**Comment by vejkse** [comment]
I’ve had the same problems with ranger in Alacritty in XMonad, but only when I launch `alacritty -e ranger` from a Python script, not from bash.

This is solved using `alacritty -e env COLUMNS= LINES= ranger`.  I learned this from this recent comment in Alacritty issues: https://github.com/alacritty/alacritty/issues/4560#issuecomment-763204194.  Here’s the qtile-dev mailing list thread mentioned in the comment: https://groups.google.com/g/qtile-dev/c/mjMKB533GNA.

**Comment by toonn** [comment]
Hmm, makes we wonder if an explicit resize event would help? And also why the initial size seems to be off while a resize signal isn't received by ranger. As long as ranger receives `SIGWINCH` I think it should rerender properly to the current size of the window.

**Comment by randomcodepanda** [comment]
I hope it's appropriate to bump this since i think it's related, i use qutebrowser,qtile and ranger for the python trifecta, qutebrowser has this feature where you can use a terminal file manager like ranger as a file picker, like when you are picking a file to upload, this has been working with no problem.

Today, Qtile upgraded to 0.30, one of the changes is that python-dbus-next is now used(don't know if it's related to the issue), but anyway as i was uploading a file i noticed the terminal text was all over the place and a window reload wouldn't fix it and i couldn't work around it but google led me here and the fix from @vejkse worked for me, i just launch ranger from qutebrowser with those environment variables and it's all good now.

The confusing part is that i thought it could be a change from Qtile but i quickly installed hyprland to troubleshoot and the same thing happened before i found this thread, so i don't know if it's that python-dbus-next package that interferes with all of this or some other package but it was working before today.
