### ISSUE TITLE
Editing file always uses $VISUAL instead of $EDITOR

### ISSUE THREAD

**Issue by chungktran** [ranger/ranger#2212]
#### Runtime Environment

- Operating system and version: Linux 4.19.128-microsoft-standard
- Terminal emulator and version: mintty
- Python version: 3.9.1
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
When pressing E to edit a file ranger uses `$VISUAL` instead of `$EDITOR`. 

#### Expected Behavior
Editing file by pressing `E` should use `$EDITOR` instead of `$VISUAL`. I have `VISUAL='bat --paging always'` for view mode and `EDITOR=vim` for editing mode. So, when editing files ranger should use `$EDITOR` but it's not. It's always using `$VISUAL`. I tried to `PAGER='bat --paging always` and VISUAL=vim` but the result is $VISUAL is still used for paging.

#### Context
I don't always edit files so I want the to view files using `$VISUAL` by default and only edit files using `$EDITOR` by pressing `E`.

#### Steps to reproduce
1. `export VISUAL='bat --paging always'`
2. `export EDITOR=vim'
3. Run range and press `E` on a file to edit. `$VISUAL` is used instead of `$EDITOR`

**Comment by chungktran** [comment]
I figured out that I can remap keys and it's behaving like I wanted.

```
map e open_with vim
copymap e E
```

I can now set `VISUAL='bat --paging always'` and it'll use bat to page and only edit when I do `e` or `E`.

**Comment by toonn** [comment]
Ranger doesn't use VISUAL for paging afaict? This is a bad idea because many programs will launch VISUAL when they want you to edit a file. (The programs that ignore VISUAL and only use EDITOR are doing it wrong.)

**Comment by chungktran** [comment]
I understand your concern with my method above. I can just not set VISUAL at all and only set EDITOR instead.

On the ranger side, according to the Wiki ranger uses `$PAGER` to page and `$VISUAL` to edit. However, I tried setting `PAGER='bat --paging always'` and `VISUAL=vim` and when I hit enter on a file it launched `vim` instead of `bat`. Looks like ranger is not using $PAGER at all. I did mention this scenario in the `Expected Behavior` section in the initial post.

**Comment by chungktran** [comment]
Actually I just tested again by setting PAGER=`bat --paging always` and I get this error: `[bat error]: Use of bat as a pager is disallowed in order to avoid infinite recursion problems`.

**Comment by toonn** [comment]
Ah, I think you're misunderstanding how rifle works. If you trigger a file it will use the first matching rule in `rifle.conf` for text files that's the editor rule because that's the most common thing people want to do with text files.

By pressing `r` you can see a list of all the rules that match. You'll see $PAGER is in that list by default but to trigger it you have to pres `r#` (where "#" is the number in the list shown by `r`). You could change the order of the rules in `rifle.conf` if you rarely want to edit text files.

However, there are the `E` and `i` key bindings. The former always opens the file in your editor, so that'd be a convenient way to still trigger editing files if you change the rule order. The latter expands the preview pane which acts like an anemic pager. In your case I'd set VISUAL and PAGER and change the rule order in `rifle.conf`, *if* bat allows you to start it from PAGER that is.

**Comment by chungktran** [comment]
I understand now. Thank you very much for explaining.

**Comment by toonn** [comment]
Np.
