### ISSUE TITLE
wezterm image preview

### ISSUE THREAD

**Issue by p00f** [ranger/ranger#2254]
Can image previews in [wezterm](https://wezfurlong.org/wezterm/) be implemented? It supports the iTerm2 graphics protocol

**Comment by toonn** [comment]
Does it work if you simply enable the `iterm2` preview_images_method?

**Comment by p00f** [comment]
No it doesn't work after installing imgcat either
I changed `set preview_images true` and `set preview_images_method iTerm2`

**Comment by p00f** [comment]
my bad it should be `iterm2` not `iTerm2`

**Comment by p00f** [comment]
(in my defense, it's written `iTerm2` everywhere in rc.conf)

**Comment by p00f** [comment]
(I didn't need to install imgcat either)

**Comment by BLumia** [comment]
Just leave a note here for people who are also using `set preview_images_method iterm2` since it works out-of-the-box with WezTerm. If you are also facing the image sizing issue, then set the `iterm2_font_width` and `iterm2_font_height` could resolve the issue [since the default font width and height is hard-coded](https://github.com/ranger/ranger/blob/master/ranger/config/rc.conf#L129). On my machine, the following configuration works pretty well:

```
set preview_images true
set preview_images_method iterm2
set iterm2_font_width 12
set iterm2_font_height 20
```
