### ISSUE TITLE
How to scale kitty image previews?

### ISSUE THREAD

**Issue by Pistrie** [ranger/ranger#2273]
#### Runtime Environment

- Operating system and version: Garuda Linux
- Terminal emulator and version: kitty 0.19.3
- Python version: 3.9.2
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
Image previews don't rescale to fit inside the terminal. Larger images will cause lag before they are fully loaded.

#### Expected Behavior
Images will be rescaled to properly show inside the terminal

#### Context
For example, a wallpaper image will not properly rescale to fit the terminal, but will instead have a piece at the side cut off.

#### Possible Solutions
I'm not sure

#### Steps to reproduce
1. Install the kitty terminal
2. Follow the steps in the image preview part of the wiki to enable image previews with kitty
3. preview a large image using ranger

**Comment by toonn** [comment]
I think this is a known issue, could you search the tracker for similar issues?

**Comment by Pistrie** [comment]
I did search beforehand but I couldn't find anything

**Comment by cho-m** [comment]
@Pistrie 

There is a GitHub issue tracking multiple Kitty preview problems. Discussion on behavior starts at: https://github.com/ranger/ranger/issues/1890#issuecomment-758115167

Also similar sizing issue #2126.

Lag could be due to lack of async. Related async issues: https://github.com/ranger/ranger/labels/wants-async
