### ISSUE TITLE
Ranger Tmux title not changed back

### ISSUE THREAD

**Issue by nkh** [ranger/ranger#228]
If the option is set, Ranger changes the title of the tmux window but on exit it does not restore the title of the window

**Comment by hut** [comment]
Is it even possible to restore the title of the tmux window?

**Comment by nkh** [comment]
you can get the name with "tmux display-message -p '#W'" and rename-window at the end of the ranger session

**Comment by randynobx** [comment]
I'm playing around with this right now and have got it partially working. The problem comes in when you run ranger outside of a tmux terminal, as you get an error message of 'cannot connect to [tmux] server'.

Unless someone can come up with a way to silently grab the name, then its going to take a big code addition just to change the tmux title back without throwing errors outside of tmux.

**Comment by randynobx** [comment]
@nkh 

This feature request will not be able to be implemented from within ranger due to the way that ranger is launched by python. 

However, you can achieve your desired functionality by tweaking your bashrc/zshrc (or whatever shell you use) to updating the title based on the current running process.

Run the following shell code to set the current tmux window title to the hostname of the machine you are running the code on.
```bash
printf '\033k$(hostname)\033\\'
```
You should be able to incorporate this in your bashrc to return the current running process instead of hostname, and then set it to run after every command (would be rather taxing) or at some set interview/event.

**Comment by randynobx** [comment]
@nkh  Here is a patch that you can apply to ranger/gui/ui.py that will offer a limited (and somewhat broken) implementation of what you asked for, since it won't be added to the official release:
https://gist.github.com/randynobx/cfcfcb697e97cac73342
