### ISSUE TITLE
A few noob questions regarding how to use Ranger

### ISSUE THREAD

**Issue by manujchandra** [ranger/ranger#2352]
Hi,

I am trying to switch to ranger. Need help with the following issues:

1. What is the second item in the ranger footer? In [this case its 1](https://en.wikipedia.org/wiki/Ranger_(file_manager)#/media/File:Ranger-screenshot.png)

2. The 5th item in the footer is date. Is it modification date? 

3. How to see time remaining when copying or compressing files (using ranger-archiver plugin)? It shows the progress bar in tasks and footer but I could not see time remaining

4. I would like to for example deep search for all files and folder with a particular name in a given folder and then do something with the results. I tried fzf but its giving problems with xonsh. I managed to get the results but I cannot cut or delete them like I can do in gnome. I tried fd also. It simple says 6 results found but does not show me any results. Is there a way to emulate nautilus functionality where we type a string and we see all the results and I can delete them or copy them (I dont want to jump to them - I can do that using fzf locate which is working)

5. In nautilus there is a feature whereby I can select some files and "New folder with selection". It will create a new folder and move the selected files in it. Is there a way to create a command for this same functionality?

Thanks in advance for answering so many questions. 

P.S: I am using Xonsh shell.

**Comment by toonn** [comment]
1. The number of files in the target, including `.` and `..`, that should probably be fixed : )
2. mtime
3. Not currently possible. It's a good idea to add mappings to conveniently call rsync or something. Ranger's copying is fairly slow and unsophisticated, I only use it for small/few files.
4. You'd have to illustrate with screenshots (you can upload them inline on github). If you're talking about the fd command from the wiki then you can jump between results with `n/N`.  You'd have to alter the command if you want filtering or selection (probably in the copybuffer because the regular selection cannot range over multiple directories, unless you `:flat` them first).
5. You could quite easily write a command for this. I couldn't come up with a mapping due to chain not waiting for previous commands to finish and paste not accepting a non-existent destination. The latter could be changed in ranger imo.

The subreddit's a better place for questions such as these. There's way more helpful folks keeping an eye out over there.
