### ISSUE TITLE
Ranger cannot open images properly with qimgv

### ISSUE THREAD

**Issue by PoisonFrog** [ranger/ranger#2406]
Runtime Environment:
ranger version: ranger 1.9.3
Python version: 3.9.6

I added these 2 lines to rifle.conf:
```
mime ^image/svg, has qimgv,   X, flag f = qimgv -- "$@"
mime ^image, has qimgv,    X, flag f = qimgv -- "$@"
```
so I could open images on qimgv. This is not my first time doing this and it always worked with other apps, but with qimgv the app opens but I get a message saying _"Could not open path: --"_ and there is no image there just the app.

It's probably just the way qimgv works idk, but it would be nice if someone knew a workaround to make this work with qimgv.

**Comment by toonn** [comment]
This is because `qimgv` doesn't support the `--` argument. It's a convention that programs stop parsing arguments for `-f`lags and `--options` when they encounter that. So every program has to implement the convention, it's not a shell feature. I think libraries like `getopt` might support the convention by default which is the reason it's so common. The reason we use it whenever possible is that if you pass a filename to `qimgv` that is also a valid option it'll be interpreted as an option and that means there's no way to pass such a file.
