### ISSUE TITLE
Ranger won't open text files when launched via Desktop entry or from rofi

### ISSUE THREAD

**Issue by wiktor-waj** [ranger/ranger#2462]
#### Runtime Environment

- Operating system and version:  Arch Linux 5.13.12-arch1-1
- Terminal emulator and version:  urxvt v9.26 | XTerm(369)
- Python version:  Python 3.9.7
- Ranger version/commit: ranger 1.9.3
- Locale: LANG=en_US.UTF-8

#### Current Behavior
When opening ranger via desktop entry or "indirectly" via commands like `urxvt -e ranger` or `xterm -e ranger`
ranger won't open text files(and only text files) when pressing 'l' or 'enter' .
#### Expected Behavior
Opening all text files with my $VISUAL when launching ranger "indirectly" or via desktop entry
#### Context

I've got keyboard shortcut setup in i3 to launch terminal with ranger in it, this is obviously malfunctioning and requires me to instead open a terminal and then launching ranger.
#### Possible Solutions
Dunno
#### Steps to reproduce
1. Launch ranger via command `urxvt -e ranger` or `xterm -e ranger` or via desktop entry
2. Try opening any text file with 'l' or 'enter' keys
3.  ???

#### Traceback

```

```

**Comment by toonn** [comment]
Hmm, I can't reproduce this (using Kitty). Can you check whether VISUAL and/or EDITOR are set? And can you run your editor from the console with shell? `:shell vim %f`

```
eval import os; self.fm.notify("{0}, {1}".format(os.getenv("VISUAL"), os.getenv("EDITOR")))
```

**Comment by wiktor-waj** [comment]
Output of VISUAL and EDITOR :
`λ ~ $ echo $EDITOR
/bin/nvim -w
λ ~ $ echo $VISUAL
/bin/nvim
`
Also I can't open those files with `:shell vim %f` but I can with `:shell nvim %f` (which is weird since I've setup bash alias for vim=nvim, I don't have vim installed on my machine btw). From what I can see my issue seems to that vim is not installed on my system but that shouldn't be a problem since I've got both EDITOR and VISUAL set.

**Comment by toonn** [comment]
No, you need to check whether they're set from within ranger. I think your terminal isn't loading the environment you think it is. Because there's no shell reading your bashrc involved. I think you'll have to duplicate your environment so it's also set by your WM, probably through `.Xprofile`.

Aliases won't work with `:shell` because ranger uses a non-interactive shell, so again the bashrc isn't loaded.

And not having a vim executable at all indeed breaks ranger's fallback behavior, as that is hardcoded. This won't be a problem if you can get the environment fixed though.
