### ISSUE TITLE
Suggest: more setting for the find feature

### ISSUE THREAD

**Issue by ForteDexe** [ranger/ranger#2570]
I would love to use up and down to select a file while using 'find'.
And it would be nice if 'find' only displays my related search, hide the rest file/folder for more visible.

**Comment by markus-bauer** [comment]
You can go up and down with Tab/Shift+Tab.
Movement in find is done by calling console_tab, which is mapped to the Tab key by default. The Up and Down keys are already mapped to history_move.
Since mappings are configurable, you could *replace* the default mapping, for example:
```
# Just an example:
cmap <UP>    eval fm.ui.console.tab(-1)
cmap <DOWN>  eval fm.ui.console.tab()
cmap <C-p>  eval fm.ui.console.history_move(-1)
cmap <C-n>  eval fm.ui.console.history_move(1)
```

I don't understand the second part of your question. 
Note that find is an alias for scout. 

    Scout Flags:
        -a    Automatically open a file on unambiguous match
        -e    Open the selected file when pressing enter
        -f    Filter files that match the current search pattern
        -g    Interpret pattern as a glob pattern
        -i    Ignore the letter case of the files
        -k    Keep the console open when changing a directory with the command
        -l    Letter skipping; e.g. allow "rdme" to match the file "readme"
        -m    Mark the matching files after pressing enter
        -M    Unmark the matching files after pressing enter
        -p    Permanent filter: hide non-matching files after pressing enter
        -r    Interpret pattern as a regular expression pattern
        -s    Smart case; like -i unless pattern contains upper case letters
        -t    Apply filter and search pattern as you type
        -v    Inverts the match

If you want to filter while typing use this, or any other combination you like:
```
alias find       scout -eitf
```

**Comment by ForteDexe** [comment]
Thank you, this is what I am looking for.
But I have a problem with scout -k, you need to type a character before you can move to select:
![Peek 2022-02-22 07-21](https://user-images.githubusercontent.com/57673412/155042148-c057232e-0b3b-435d-82bb-b1486ddabb23.gif)

**Comment by markus-bauer** [comment]
Yes, this is how scout works at the moment. You can try it with all scout commands: Scout ignores tab when there's no input.

I agree with you that this is not what the user expects. It should match everything when there's no input, instead of nothing.
But I think you would need to change the code for this to work.

I decided to make a separate issue for this:  #2575

**Comment by ForteDexe** [comment]
@markus-bauer Thank you for helping me describe and make a report :D.

**Comment by markus-bauer** [comment]
A final note:
You can map almost anything to anything. But you have to experiment for yourself.
For example, you can actually move the cursor while the console (and scout) is active, like this:
```
# cmap is the mapping while the console is active. 
cmap <UP>       move up=1
cmap <DOWN>     move down=1
```

**Comment by ForteDexe** [comment]
@markus-bauer hey that fixed the issue, thank you very much :D

**Comment by toonn** [comment]
Thanks to @markus-bauer for helping to fix this issue!
