### ISSUE TITLE
Extended support for Finder

### ISSUE THREAD

**Issue by Bellavene** [ranger/ranger#2673]
[Findger](https://github.com/Bellavene/findger)
A Ranger plugin that adds support for macos Finder. Best used along with auto tiling window manager. Uses finder to preview virtually anything, the rest depends on Quicklook plugins you use. Don't judge hard, I am not a coder, just wanted some features and made them as I could. Any advices are welcome.

Features:
```
  1. Support of any file preview right in Finder with Gallery view mode.
  2. Reveals selected file from active Finder window to Ranger.
  3. Reveals selected files from Ranger in Finder. (Code from Ranger's wiki)
  4. Toggle red Finder's and Ranger's tag on selected files. (Needs a dependency)
```

Todo: Add better cross support for Finder's color tags.

<img width="2128" alt="Screenshot 2022-07-18 at 13 55 41" src="https://user-images.githubusercontent.com/77557804/179497347-9f0ba654-f6dc-4c17-834d-77e5b5d670fd.png">

Sorry for making an Issue, just wanted to share the code and maybe someone will give an advice to perfect some things.

**Comment by toonn** [comment]
Hi, this seems pretty cool :sunglasses:  I believe someone else recently submitted a PR implementing previews using QuickLook. You might want to search for that PR, maybe you'll find something to borrow from it or something to suggest to improve it.

I'm going to close this issue because issue reports aren't really an appropriate venue for promoting plugins and such. Consider posting to the r/ranger subreddit and adding it to the plugin list on our wiki here on GitHub.

**Comment by Bellavene** [comment]
Thank you. I know that it was not the right place. Will try to add it to the wiki if I will get free time. And as I am not a coder, was blindly writing it with zero knowledge in python, will be glad if someone will help make it in the right way, as for now key maps bother me with its dirty code : )
