### ISSUE TITLE
Ranger opens another editor instead of default when launched via desktop

### ISSUE THREAD

**Issue by 1stGuardian** [ranger/ranger#2687]
#### Runtime Environment

- Operating system and version: Fedora 36
- Terminal emulator and version: kitty 0.25.2 created by Kovid Goyal
- Python version: Python 3.10.5
- Ranger version/commit: ranger 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
Ranger opens nano instead of $VISUAL or $EDITOR which is nvim
#### Expected Behavior
Ranger opens text files with nvim
#### Context

1. Ranger works as normal when launched via terminal, It opens text files with nvim
2. As i wrote above, when launched via desktop and i open text files, it will open nano instead of nvim. Then i try to open terminal with ```S``` and echo $VISUAL and $EDITOR where the output is nvim

Why this is happen?

**Comment by toonn** [comment]
Did you figure out what was wrong?

The environment in which Ranger was started must've had one of those variables set to `nano`, because there's no other source for Ranger to get that program from. Unless you're on a Debian-derivative and Ranger was patched to use `sensible-editor`.

The reason the shell spawned from inside Ranger reports the variables correctly is that that shell loads your `.bashrc` or equivalent and that's probably where you are setting those variables.

The r/ranger subreddit is a better place for user questions like these. There's a community of users forming there slowly so usually you get answers faster.
