### ISSUE TITLE
Slow initialization in /nix/store and hanging when shortcut guide window opens on NixOS

### ISSUE THREAD

**Issue by the-argus** [ranger/ranger#2753]
#### Runtime Environment

- Operating system and version: NixOS 22.05
- Terminal emulator and version: kitty 0.25.2
- Python version: 3.9.15
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior

1. when opening ranger in _any_ subdirectory, no matter how deep, of ``/nix/store`` (a directory which is mounted read-only and contains a large number of subdirectories) results in a long startup time where the terminal just reads ``loading... rangerranger``
2. When typing ``dd`` to copy selected files, or ``dD`` to delete them, and other such vimlike operations which bring up the shortcut guide window, lag occurs and the shortcut guide takes a long time to show up. Additional keystrokes (such as the second ``d`` in ``dd``) do not register until the initial lag is done. Even when the operation completes, it can fully or partially fail. For example, a copy with ``pp`` can paste some of the selected and cut files but leave others behind.

#### Expected Behavior

1. I open a direct child directory of /nix/store, and maybe there is some lag during initialization since ranger previews the parent directory's contents. However, if I open a deep subdirectory of a large directory, ranger should only read the working directory and start at normal speed.
2. I press ``d`` and then the shortcut guide window pops up for a split second before I press ``d`` again, completing the cut operation. Typing ``pp`` in another directory removes all of the original cut files and places them in the pwd.

#### Context

I am copying images between wallpaper github repositories. They are somewhat large and cause general unresponsiveness in ranger when scrolling as it freezes on each file to render the preview in kitty. I believe the size of the files and the hanging due to image previews is causing the issue.

#### Steps to reproduce

If you have a working nix installation, you can replicate my ranger installation by 
1. cloning [my configuration flake](https://github.com/the-argus/nixsys) and 
3. checking out commit ``6f78970f0edc42c31b6f988389bdb9ddbcd90a7b``. 
4. run ``nix run --inputs-from /path/to/laptop-config nixpkgs#ranger -- /nix/store/nrwa1i20aw6b2hbhy8q6mjmdmx8m5hns-ranger-1.9.3/lib/python3.9`` (replicates issue 1)
5. cd to your home directory, clone [a wallpaper repo](https://github.com/makccr/wallpapers/) to get some big images , and ``dd`` and then ``pp`` them onto your desktop. Should replicate issue 2

**Comment by the-argus** [comment]
just use ``lf`` instead of ranger. ``lf`` previews parent directories and the selected file on a different thread, so this isn't a problem.

**Comment by toonn** [comment]
The former is due to ranger stating everything up to root. So in a subdirectory of `/nix/store` it will stat *all* of the directories in `/nix/store` which is usually very many. This is a known issue and will be fixed eventually but it is a bit of an edge case so it's not a very high priority. Running Ranger with Pypy does help performance in this case *immensely*, it's worth trying out if you're running Nix anyway since it's so easy to override the pythonPackages passed into the derivation.

The second is due to the design of the copy_buffer. Every byte of file copies goes through Ranger, this means Python is reading things into memory and then writing it back to disk. This is another known issue with fairly low priority because it's so easy to bind keys to an rsync invocation for example.

Enjoy running lf though if suits you better.
