### ISSUE TITLE
Draw blank spaces for draw_borders?

### ISSUE THREAD

**Issue by mqrris** [ranger/ranger#2829]
I recently changed my image preview method from ueberzug to kitty and the border lines started to flicker and then disappeared as I scrolled back, I realized how clean it looks without the lines. I'm really hoping for a way to remove the lines without affecting the padding they add.

![image](https://user-images.githubusercontent.com/71521628/235327608-04654f70-4fe3-40b5-bf4c-8910a7ae1d8c.png)
![image](https://user-images.githubusercontent.com/71521628/235327609-084acc06-0017-4ea9-9602-39c280e7eb68.png)

**Comment by toonn** [comment]
This isn't configurable but it's actually fairly easy to patch:
[0001-widgets-Replace-border-drawing-characters-with-space.patch.txt](https://github.com/ranger/ranger/files/11407716/0001-widgets-Replace-border-drawing-characters-with-space.patch.txt).

I had to add the `.txt` extension because GitHub's file upload doesn't seem to work with `.patch` even though the error explicitly tells me to "Try again with one of [...] PATCH [...]."

**Comment by mqrris** [comment]
Thank you, I'll patch it and see if it works!

**Comment by mqrris** [comment]
I patched the `view_multipane.py` file, then did `doas make install`, but the lines are still there. I tried "both" and "outline" in `rc.conf`

**Comment by mqrris** [comment]
Yay, it works! I just added 
```
if 'outline' in border_types:
            # pylint: disable=no-member
            self.addch(0, left_start, " ")
            self.addch(self.hei - 1, left_start, " ")
            self.addch(0, right_end, " ")
            self.addch(self.hei - 1, right_end, " ")
            # pylint: enable=no-member
```
to `view_miller.py`

**Comment by mqrris** [comment]
All that was needed is to replace all `curses.*` to `" "`
