### ISSUE TITLE
how ranger deals with shell history

### ISSUE THREAD

**Issue by alikthename** [ranger/ranger#2857]
it's not quite clear what's happening when I switch to shell in ranger (with 'S')
I run some commands in that shell
then exit shell and exit ranger
type 'history' in the parent shell and it's only 'ranger' there

start ranger again, type 'S' entering the shell
run 'history' there it is, I can see history from previous ranger 'session'

so 2 questions:
- where is shell history saved when ran 'inside' ranger
- how can I merge that history into outer ~/.bash_history

**Comment by toonn** [comment]
Ranger starts a subshell. So you should be able to test by just running a new shell from your shell, without Ranger involved at all. I think running shells don't tend to synchronize history, it's only upon starting that they load the history into memory.

This isn't really a Ranger issue so I'm going to close it. Questions like these are more appropriate for the r/ranger subreddit and tend to get quicker responses there because there's more community members. If you do solve your problem you can feel free to post a comment with your soluion though.
