### ISSUE TITLE
ranger 1.9.4 tarball seems to be unavailable

### ISSUE THREAD

**Issue by andrelcmoreira** [ranger/ranger#3023]
Hi folks, I figured out the version 1.9.4 was released yesterday. However, I'm trying to download it from https://ranger.fm/ranger-1.9.4.tar.gz and I'm getting a 404 error. Somebody else with the same problem?

**Comment by alerque** [comment]
Yes. Arch Linux packaging is waiting for this too. The link is posted but the tarball is 404. We use this source because it's the one that is supposed to be GPG signed.

**Comment by eMPee584** [comment]
.. don't hold your breath, it only contains a single fix from the 700+ commits made to master in the last five years..
hopefully, in the near future, AI support (or 👽s) can revitalize the project..

**Comment by alerque** [comment]
This issue was fixed within 1 hour of [reporting it on the website issue tracker](https://codeberg.org/ranger/pages/issues/1).

I don't know what to say about the release not having anything of substance relative to 5 years of development. Maybe a separate issue can be raised about that, but this one can be closed as fixed.
