### ISSUE TITLE
Ranger crashes if the Current Directory (CD) has been deleted

### ISSUE THREAD

**Issue by expenses** [ranger/ranger#424]
Simply put, if the user cds to a directory which is later deleted, and attempts to launch ranger, ranger crashes. Tested on Archlinux 4.2.5-1 with ranger 1.7.2-1.

```
mkdir ~/test
cd ~/test
rmdir ~/test
ranger
```

**Comment by phimuemue** [comment]
I think I found the reason and would probably like to fix it:

`main.py` contains a line 

    fm = FM(paths=targets)

which apparently is used to initialize the file manager. This call, in turn, assumes that `targets` contains valid directories (are passed to `abspath`).

As a first step, I would suggest to proceed only if all `targets` are valid and cancel otherwise. We could display a clear message indicating which directory is invalid, so that the user knows the exact reason why things fail. What do you think about that?

As a second step, we could think about the following:
* If `~/path/to/dir` does not exist, we could simply create it.
* If `~/path/to/dir` does not exist, but some prefix (e.g. `~/path`) of the path does, we could "go up" to the existing directory.
* If some targets are valid and others are not, we could just choose the valid ones.

However, imho all those things can be unexpected to the user, so they should possibly be customizeable. Do you have opinions regarding such strategies?

**Comment by expenses** [comment]
This should be customable, I agree. By default it would make sense to cd the containing (higher) directory instead, but it would be a nice feature for some users if ranger created the directory if it did not exist.
