### ISSUE TITLE
w3m preview glitches in st+compton for shrinked images

### ISSUE THREAD

**Issue by amerlyq** [ranger/ranger#438]
Therefore, my test cases on ArchLinux:
- urxvt w/ or w/o compton -- shows any images (small and large) smoothly
- st w/o compton -- shows as urxvt, all ok
- st with compton and images smaller than max_width_pixels*max_height_pixels -- smoothly
- st with compton and image width/height bigger than viewport -- glitches.

See actual results (Edit: bigger actual image):
![glitches](https://cloud.githubusercontent.com/assets/5730096/12004605/534015fa-ab6f-11e5-8098-dbedc515ab6b.jpg)
There you can notice black oblong glitches, looking like wrong image width detection for alpha-channel, which results in shifting of image alpha for each pixel row. But problem is: there is no alpha in jpg image and alpha for st window is exactly the same.

I have tried to use smaller arguments inside `ext/img_display.py` like `max_width_pixels-=20; max_height_pixels-=20` with no result. Back then I thought the reason was in st using 2-pixel wide black border around its window.

Therefore, I appreciate any suggestion how to mitigate this problem, as I can't understand where issue located in this whole toolchain: `Arch -- X -- compton -- st -- ranger -- w3mimage`.

By the way, original image looked as next. 
You need window width smaller than 1400px to reproduce issue with exactly this image.
![wide](https://cloud.githubusercontent.com/assets/5730096/12004584/2d634674-ab6d-11e5-92ad-f9d544d976ae.jpg)

**Comment by krompus** [comment]
I've run into this same issue, `Arch -- X -- compton -- urxvt -- ranger -- w3mimage`

Although, for me, it's at all sizes, also happens in xfce-terminal, and happens in urxvt with compton.

When I kill compton, everything is fine, and w3m displays images as without problems, so I'm thinking it's an issue with ranger itself. Here's an example screenshot - urxvt running ranger on the left, and urxvt running w3m on the right, compton enabled.

https://i.imgur.com/Jf2yDAg.png

Have you discovered a fix or a workaround? Cheers!

**Comment by DerVerruckteFuchs** [comment]
I've noticed the alpha-channel issue with, `Arch -- X -- compton -- termite -- ranger -- w3mimage`.
It does not exist when it's `Arch -- X -- compton -- urxvt -- ranger -- w3mimage`, or `Arch -- X -- termite -- ranger -- w3mimage`.

I use `rxvt-unicode-patched` from the AUR, so that may be why the issue does not show up with urxvt in my testing.

It may be how compton and terminals interact with each other that cause this, or how w3mimage + terminal interacts with compton.

More testing should be done with w3m rendering images while running compton to see if it's a w3m issue, a compton issue, or w3m + compton. The interesting wrinkle is that using `rxvt-unicode-patched` somehow gets rid of the issue.

**Comment by DerVerruckteFuchs** [comment]
It has something to do with 32 bit color depth. Disabling 32 bit color depth, or using a different depth should work as a workaround for now. It didn't show up as an issue for me in urxvt because I wasn't using 32 bit color dept, but it termite it does show up as an issue since it uses 32 bit color depth by default.

**Comment by krompus** [comment]
Darn. I just switched to termite and I love it. I also started using compton and transparency.

How did you switch termite's color depth?

I just installed rxvt-unicode-patched, and the issue is there when I have `URxvt*depth: 32` in `~/.Xresources`, so I'm not sure what you mean. When I remove this line, the terminal becomes opaque, and images render correctly.

**Comment by DerVerruckteFuchs** [comment]
Just removing the `URxvt*depth: 32` in `~/.Xresources` is a workaround for it is what I mean. It affects all terminals using 32-bit color depth. If other programs/terminals let you switch the color depth, then you can use it as a workaround there as well. There is no option available at the moment to switch termite's color depth.

The only way I can get the alpha channel issue to go away in termite is to disable compton at the moment. You could try other compositors like xcompmgr to see if that works. The problem may be with compton, w3mimage, or possibly even X11. Testing out another compositor could help rule that possibility out.

**Comment by DerVerruckteFuchs** [comment]
If you don't mind using ascii previews instead of full image previews, that can be used as another workaround.

**Comment by nfnty** [comment]
Continue discussion in #86.
