### ISSUE TITLE
VCS integration: doesn't update file status after commits

### ISSUE THREAD

**Issue by tobanw** [ranger/ranger#481]
The VCS indicators next to files don't update after staging and committing. For example, I'll use ranger to navigate to a git repo, then press `S` to drop into a shell session, do my `git add` and `git commit`, then exit the shell which returns me to ranger. But upon return, ranger won't show the updated VCS indicators. Same for if I did the git stuff in a separate terminal. I have to restart ranger to get accurate indicators after making git changes.

I know I can use the `stage` and `unstage` commands in ranger (it will correctly update the VCS indicator), but there's no `commit` command.

In `ranger.conf` I have the usual

```
set vcs_aware true
set vcs_backend_git enabled
set vcs_backend_hg disabled
set vcs_backend_bzr disabled
```

**Comment by hut** [comment]
Please postpone any efforts of fixing this until #408 and #468 are merged.

**Comment by nfnty** [comment]
There is no way for ranger to update the git information automatically when only repo metadata has changed (works just fine when a file inside the repo has changed) without running into major issues. Continuously polling has been tried and causes high IO and CPU load and also blocks external applications during every poll due to file locks. To properly implement this would require a library that watches the repo metadata and updates in a very smart way. I'm not sure it's even possible with the way that git currently works (git only locks during small periods and will fail if a lock appears in the middle of a command, i.e. when running rebase).

Currently you need to manually update the VCS information inside ranger when only the repo metadata has changed by running the command `reload_cwd` (default mapped to `R`) or `reset` (default mapped to `<C-r>`).

I'll close this for now.

**Comment by tobanw** [comment]
Thanks for the update. I'll just stick to manually updating the VCS info for now.

What about adding a `commit` command that triggers an update of the VCS info upon completion?

**Comment by nfnty** [comment]
I'm mostly against committing from inside ranger due to not having a way of seeing what is actually being committed and also because it's very dynamic what you want committed.

On the other hand you can already accomplish what you want by mapping `chain shell git commit; eval fm.ui.vcsthread.process(fm.thisdir)`

You can also add macros to the command if you only want to only commit the selection (`%s`) or the current file (`%f`) etc.

**Comment by tobanw** [comment]
Thanks, I'll try that out!

I was thinking of using ranger to `stage` and then `commit`, which would open up an editor to edit the commit message (and where you can see what is being committed).

**Comment by nfnty** [comment]
Okay, then the command I posted is exactly what you want.

**Comment by tobanw** [comment]
For the benefit of anyone else who wants to add this functionality: the method that @nfnty posted above is for mapping a keybinding. To create a `:commit` command, add this to your `commands.py` file:
```python
class commit(Command):
    """:commit

    Commits the git repo and refreshes the ranger vcs info.
    """

    def execute(self):
        # opens up editor for commit message
        self.fm.run("git commit")

        # refresh vcs info
        self.fm.ui.vcsthread.process(self.fm.thisdir)
```

**Comment by nfnty** [comment]
@tobanw You don't need to create a new command for that, just use an alias. Add this to your `rc.conf`:
```
alias commit chain shell git commit; eval fm.ui.vcsthread.process(fm.thisdir)
```
