### ISSUE TITLE
Navigating while typing

### ISSUE THREAD

**Issue by suhr** [ranger/ranger#573]
I have an alias:
```
alias sieve scout -efts
```
While it is pretty nice to use, there's a problem: I can't navigate filtered results with up/down arrows. Of course, I could use `scout -pts` together with `clear_filter_on_dir_change` option on, but it adds additional keystroke. So it would be nice to be able to navigate while filtering.

Also, sometimes mc-style navigating while typing a shell command can be useful too.

**Comment by Vifon** [comment]
You can navigate the search results with <kbd>Tab</kbd> and <kbd>Shift+Tab</kbd>. It's specific to `:scout` though so it won't work with the shell commands. A more general solution would be adding this to your rc.conf:

```
cmap <a-p> move up=1
cmap <a-n> move down=1
```
 It should bind <kbd>Alt+p</kbd>/<kbd>Alt+n</kbd> in the command mode so that they will move the file cursor up/down. Of course you can use any other keys for that.

**Comment by suhr** [comment]
Thank you. I tried to bind `history_move` to `<C-up>` and `<C-down>`, but ranger prints `[1;5A` and `[1;5B` instead of recognising the key binding.

**Comment by hut** [comment]
Opened #574, a request to implement binding of ctrl+arrow keys
