### ISSUE TITLE
Research/Implement native image previews for Terminology

### ISSUE THREAD

**Issue by hut** [ranger/ranger#581]
Nobody nagged us about this yet, but ranger could use terminology's native image preview support instead of w3m for extra awesomeness.

**Comment by DaBlitzStein** [comment]
+1 to this. Terminology is the most awesome terminal I used. Please, add support.

**Comment by Dinozor** [comment]
+1
currently trying to find out a way how to implement it manually

**Comment by l00kanio** [comment]
+1. Terminology + Ranger seems to be such a great combo

**Comment by toonn** [comment]
Status update: There is previous work on this in #865, it's just incomplete.

**Comment by aztlan2k** [comment]
+1,  curious if any progress was ever made on this?

**Comment by aztlan2k** [comment]
I tried it with `ranger` v1.9.0 and it didn't work for me.  I got a whole lot of garbage on the screen.   This was against `terminology` v0.9.1 on Ubuntu 17.10.

![image](https://user-images.githubusercontent.com/4225823/38275661-2a756004-3758-11e8-80dc-97c5d8e5ad41.png)

**Comment by toonn** [comment]
@aztlan2k Are you using screen/tmux? I get a similar result with tmux. It somewhat works outside of tmux but the alignment's top left corner, so it overlaps the other two columns. Annoying as a default but could still be used if you just toggle it with `zi`.

**Comment by aztlan2k** [comment]
@toonn , yes, I was using tmux, which i normally do.  

I tried it without tmux and you are right, it works. Images, including `*.gif` animations, displayed just fine. I didn't see any issue with the image overlapping the first two columns though.  This was `ranger` v1.9.0.

![image](https://user-images.githubusercontent.com/4225823/38311741-8da55584-37e5-11e8-873f-4cb1fa39297d.png)

Thanks for pointing out that it was tmux causing the issue. It's unfortunate that it doesn't work within tmux since I use it almost on a daily basis.
