### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by nfnty** [ranger/ranger#599]
What do you think about using Travis-CI with tox, pytest, flake8 and pylint?

**Comment by Vifon** [comment]
Partially done, thanks for the idea. db6866797bd91b8dde8ecd535ab1a490a1d200db

For now it only runs `make test` since pylint & co. would probably show all kinds of warnings right now.

**Comment by nfnty** [comment]
Nice! Could you also enable CI for all PRs?

I'll start working on implementing tox and making ranger flake8 and pylint compliant. What max line length should we use? IMO 99 (100 including newline) is the most convenient.

**Comment by Vifon** [comment]
> Could you also enable CI for all PRs?

It's already enabled but not for the past PRs. All the future ones will get checked.

> What max line length should we use? IMO 99 (100 including newline) is the most convenient.

I usually strive for 70-80 but everything is better than inf. @hut?

**Comment by lamarpavel** [comment]
79 (80) works well for https://github.com/The-Compiler/qutebrowser/

**Comment by nfnty** [comment]
ping @hut

**Comment by hut** [comment]
The line length limit is 79, as pep8 dictates. It's not consistently implemented in ranger though, even by myself.

**Comment by nfnty** [comment]
pep8 states that 79 or 99 is okay.

**Comment by lamarpavel** [comment]
With reasonable font size (9-11) on a 1080p screen you can have three 79-line windows next to each other in vim, with 99 you can have two. I don't know what to prefer here, honestly. My settings in vim are adjusted for 79 because that is the only style I have seen enforced yet. Maybe going for the common option is best here, though I have only my gut feeling for what is most common.
