### ISSUE TITLE
New image preview method: urxvt background images

### ISSUE THREAD

**Issue by hut** [ranger/ranger#632]
ranger could display images in urxvt by setting the terminal background image as discussed here: https://marcocheung.wordpress.com/tag/ncmpcpp/

in summary, a simple ```printf "\e]20;/path/to/your/file;\a"``` should do the trick, in a urxvt compiled with ```--enable-pixbuf```

**Comment by Vifon** [comment]
Closed with #678.

**Comment by copycat-killer** [comment]
@Vifon Nice to have this, but I have two issues:

* [focusing](https://linx.li/86s40a3i.png) on an image will cause to rub it on the last tab: how can we have a thumbnail preview like w3m one?
* when unfocusing, the background [still persists](https://linx.li/aisvct11.png): how to *flush* it?

**Comment by Vifon** [comment]
The first issue is tough to eliminate because while all the other previewers use the absolute coordinates for the offsets and scaling (in pixels), this one needs them in percents. It's non-trivial to add a fixed offset (the height of the ranger top bar).

I cannot reproduce the second issue. All the usage examples for this urxvt features place the image at the +1000+1000 offset (again, in percents!) to disable the background. All things considered, +1000% shouldn't be inside the terminal in any case, ever. Can you share your urxvt configuration?

**Comment by copycat-killer** [comment]
> It's non-trivial to add a fixed offset (the height of the ranger top bar).

What would be the steps? I'd like to try patching it.

> Can you share your urxvt configuration?

[Here](https://github.com/copycat-killer/dots/blob/master/.Xresources).

**Comment by Vifon** [comment]
I cannot reproduce even with your config. :/

The problems are as follows. The image's center serves as a single control point. This center's position depends on the image size: on a larger image it will be further down and to the right than on a smaller one. This affects both the scaling and positioning. The image below should demonstrate it (also, I hate you, Inkscape!):

![drawing svg](https://cloud.githubusercontent.com/assets/624347/19416270/f9e621a0-938c-11e6-8489-6e22aa326634.png)

And remember that all these coordinates are in percents, not in pixels. Things that are easy with such reference frame: "align the image right", "occupy the horizontal 1/3 of the terminal". Things that for me seem to be not so easy: "leave a 10px margin on top". Unless I'm making simple stuff more complex than it really is.

**Comment by copycat-killer** [comment]
Thanks for your time. I'll give it a look ASAP.

> I cannot reproduce even with your config. :/

I guess it must be related to my gtk-pixbuf and/or urxvt building then, mph.
