### ISSUE TITLE
Using vimcat to show syntax highlighted file previews

### ISSUE THREAD

**Issue by doronbehar** [ranger/ranger#657]
This issue is not exactly regarding ranger. I just need some help with my `~/.config/ranger/scope.sh`. I think everyone can benefit from reading this. I'm trying to find the best console syntax highlighting printing tool and use it for `ranger` and regular use.

I've managed to use the defualt `highlight` by [andre-simon](http://www.andre-simon.de/doku/highlight/en/highlight.php) and I wasn't quite satisfied. I've also managed to use GNU's `source-highlight` tool which is more configurable and a little better but lacks some basic file types syntax rules and it's quite hard to create them. Anyway I've come to the conclusion that [`vimcat`](https://github.com/ofavre/vimcat) (unfortunatly less known) is perfect for this job. It ridiculously simple and has almost zero dependencies (for most of us) because it uses only vim and bash while the output is fantastically beautiful.

The problem is that I don't see colors in the file previews while I try to use it for `ranger`. This is how my `~/.config/ranger/scope.sh` looks like in `$mimetype` case:

``` bash
    # Syntax highlight for text files:
    *)
        try vimcat "$path" && { dump | trim; exit 5; }
        ;;
esac
```

**Comment by yossizahn** [comment]
I had the same problem, fixed it by commenting out lines 7-10 of the vimcat script. I find the speed of vimcat to be terrible on large files. I'm still looking for a good console syntax highlighting printing tool.

**Comment by Doron-Behar** [comment]
I dropped `vimcat` and I use [`source-highlight`](https://www.gnu.org/software/src-highlite/) (also known as `src-highlite`). It's written in CPP and I find it much faster than `python-pygments` and better documented than the defualt `highlight` by [andre-simon](http://www.andre-simon.de/doku/highlight/en/highlight.php). Here's my [scope.sh](https://github.com/Doron-Behar/dotfiles/blob/master/.config/ranger/scope.sh#L94), It is inspired by a shell small script available after installing the package on your Linux distribution. The script should be found in `/usr/bin/src-hilite-lesspipe.sh`.

**Comment by Rom1deTroyes** [comment]
On Thursday 27 Oct 2016 à 14:08:59 (-0700), yossizahn wrote:
> I'm still looking for a good console syntax highlighting printing tool.

I use this since a couple of days...
https://github.com/huyz/less.vim
... Not having problem at this time.

Maybe a way to explore ?

++
    Romain
-- 
Aimez donc la raison ; que toujours vos écrits
Empruntent d'elle seule et leur lustre et leur prix.
	-+- Nicolas Boileau, Art poétique -+-

**Comment by peey** [comment]
Hi. Could this be reopened? I'm trying to use this as well but there's still no answer on how to make it work. When I replace highlight command with vimcat, it doesn't show colors. 

I think it has to do something with how colors are represented in the terminal, for instance if I add this line above the highlight command 

```
printf "\x1b[38;2;255;100;0mTRUECOLOR\x1b[0m\n"
```

Then it doesn't print with color, however it does print colors when I do 

```
            for i in {0..255}; do
                printf "\x1b[38;5;${i}mcolour${i}\x1b[0m\n"
            done
```

Is this related to https://github.com/ranger/ranger/issues/690? 

Is there any utility which can automatically convert vimcat's truecolor output to this 256 color format?

Ping @nfnty  @toonn

**Comment by doronbehar** [comment]
I think this can be configured through Vim for only when `vimcat` is being run.

**Comment by peey** [comment]
@doronbehar Any ideas how? I tried changing the vimcat command to

```
TERM=xterm-256color vimcat ${FILE_PATH}
```

And also tried various other values for `TERM`. No luck. `vimcat` also provides a `~/.vimcatrc` for custom vim configuration while running vimcat, but I don't think we can affect colors from within the `vimrc`

**Comment by doronbehar** [comment]
Do you use Vim or Neovim? As for Vim I'm not sure but I know Neovim has `termguicolors`. Read it's `:help` I think if it's set by default in your `~/.config/nvim/init.vim` you should turn it of in `~/.vimcatrc`.

**Comment by peey** [comment]
Nope. I use vim and not neovim. Apparently `termguicolors` is unset by default, so it shouldn't be a problem. I tried setting and unsetting it with vimcat and it had no effect (but it did have effect in vim)

I'm now tired trying to make this work, I'm just gonna wait for a word from maintainers. Might shed more light into why it doesn't work. I just want to use vimcat because I don't want to see same code highlighted differently when I'm reading it in ranger or editing it in vim.

**Comment by doronbehar** [comment]
I don't think they'll have better clue than you.. BTW, what version of vimcat do you use? I've found a few when searching the web.. Perhaps you should try [less.vim](https://github.com/huyz/less.vim) which was mentioned in [a previous comment](https://github.com/ranger/ranger/issues/657#issuecomment-256882690).

**Comment by peey** [comment]
@doronbehar I tried `less.vim`. Unfortunately it doesn't exit (much like less) and I think it's important for highlighting script to exit so that we can exit with code 5, that's how the original highlight and pygments command are.

@toonn ofavre/vimcat did not produce any colors for you in regular use (not within ranger)? Interesting. What terminal emulator are you using? If you're using tmux then can you try vimcat outside it and see if it works? I think your terminal might have the same limitations which we have to adhere to for this to work with ranger

I already tried vimcat with `-c` / `--colors` options, it doesn't work sadly.

Also if this feature is desirable in general, then could you open this issue? If not me then someone else might send a PR if they're able to do it. I saw #1394 , it does seem very similar.

P.S. add the following to your `~/.tmux.conf` to enable trucolor support if it works in your terminal. Found it [here](https://github.com/tmux/tmux/issues/34#issuecomment-360952917) and it works with fish.
```
set -ga terminal-overrides ",*256col*:Tc"
```

**Comment by toonn** [comment]
Vimcat didn't work outside tmux either, with and without ssh. Meanwhile vim has zero problems with tmux/ssh so I blame the tool. I'd expect it to work with `-c256` since other previewing methods that output 256 colors work, did you try other values for this option, like `16` or `8`?

Reopening this issue is pointless imo. If someone implements working vimcat previews they can just PR. It's not like open issues are easier to find when there's almost 300 open issues already.

**Comment by toonn** [comment]
Closed doesn't mean solved and I assume they'd read the conversation to figure out the solution anyway.

It's a reddish orange for me. (Might be my color configuration.)

**Comment by doronbehar** [comment]
@peey, I'm not sure exactly how vimcat works but I'm pretty sure you'll never succeed in the attempt to make it work from within ranger. The reason is that I'm pretty sure it doesn't actually print ANSI colors, I think what it actually does is just 'opening' a vim window and sort of scrolling to the bottom of it in a way that looks as if it was printed in your terminal. That's the reason why I dropped it in favor of the default (and fast) `highlight` utility.

I agree vimcat is super cool because it uses your preferred vim colorscheme and other settings but I think you are facing a dead end.

As for the debate in reopening the issue or keeping it closed, my opinion is that it should remain closed as "won't fix" because of the same reason I explained above.

BTW, if anyone is interested in having a tool that will highlight code with the same settings and colors as Vim, one should reuse the code of Vim itself and extract the relevant source code that will parse only the colorschemes and syntax highlighting definitions and just `printf` the code with the right color codes... That's much more complicated but not impossible in comparison to `less.vim` and vimcat which are essentially scripts.

**Comment by peey** [comment]
@doronbehar ah, I hadn't thought of that. But I tested this theory I redirect the output in this way `vimcat file.js > coloredfile` and then do `cat coloredfile` then I'm still able to see colors. So it seems I can redirect my output. But if I do the same from within `scope.sh` then I just see white text. Do you think this should happen? 

This does rule out the case that there's something wrong with color output in ranger. Because then I should be able to see color output when I cat the file outside of ranger. It seems that vimcat just doesn't produce colors when called from within `scope.sh`.

**Comment by peey** [comment]
Some more debug info (if vimcat is already giving you colors). In a file named `test.sh`, write

```
#!/usr/bin/env bash

indirection() {
  echo $1;
  vimcat $1 > colors;
}

indirection $1;
```

Then execute 
```
./test.sh ./test.sh
cat colors
```
For me the cat command does give colored output. So this confirms to me that vimcat is working fine.

I also tried to wrap it in a python file `test.py`

```
import subprocess
subprocess.call(['./test.sh', './test.sh'])
```

And if you execute

```
python test.py // works with both python 3 and python 2
cat colors
```
Then it also works. So I think it's something special about the environment that `scope.sh` is called in (be it ncurses or whatever. I'm not sure) that vimcat isn't producing colors because maybe in that environment it thinks that color isn't supported.

Also  if you put the following in `scope.sh` just above the `highlight` command, you'll see that it doesn't produce any color (but on your normal terminal it would)
\
```
printf "\x1b[38;2;255;100;0mTRUECOLOR\x1b[0m\n"
```

**Comment by toonn** [comment]
Like we've said ranger doesn't support TRUECOLOR escape codes, because of ncurses. Previewing the colors file should give a plaintext preview in ranger, if it uses color codes that ranger/ncurses understands you should see it colored. For example, try generating one with highlight and a couple with different options for vimcat and check whether the output of highlight previews with color in ranger. Then find the options that result in similar color escape codes with vimcat.

**Comment by peey** [comment]
@toonn In fact if I invoke vimcat on my terminal, put the output in a file and then replace `highlight` by `cat` in `scope.sh`, I see colors!

At the same time
1. `vimcat` doesn't produce colors when invoked from curses environment
2. The `TRUECOLOR` escape codes do display plainly within the file but  if I append it to a file from within `scope.sh` and then cat that file in my teminal, then it works.

At this point I think there are 2 separate issues. 

1. vimcat doesn't produce colored output when invoked from curses environment. I'll open an issue in vimcat for this. I don't think there is anything ranger maintainers can do here.
2. Truecolor support in vimcat due to ncurses (due to https://github.com/ranger/ranger/issues/690)

And I now think that these two aren't related. Unfortunately there's no resolution in sight, but thanks to all for helping out and being patient as we figured this out.

**Comment by Rom1deTroyes** [comment]
Hello there, and thanx for all your great work and this tool !

Just in case it could help, I got this :

- gnome-terminal with solarized-dark background palette and solarized palette
- urxvt-unicode-256color with solarized-dark colors in .Xdefault

> printf "\x1b[38;2;255;100;0mTRUECOLOR\x1b[0m\n"

- urxvt : White
 - TERM=rxvt-unicode-256color
 - COLORTERM=rxvt-xpm
- urxvt with tmux : Orange
 - TERM=screen
 - COLORTERM=rxvt-xpm
- gnome-terminal : Orange
 - TERM=xterm-256color
 - COLORTERM=truecolor
- gnome-terminal with tmux : Orange
 - TERM=screen
 - COLORTERM=truecolor

> is orange-ish for you or the default text color (white)? 

Well, as a side effect, I discover that reply a message with mutt under
tmux in urxvt solve the problem I had with scpacevim theme : now I'm
free from gnome dependency (and a lazy guy on this :-) ).

++
    Romain
