### ISSUE TITLE
Is there a way to copy many filenames to the clipboard at once?

### ISSUE THREAD

**Issue by krompus** [ranger/ranger#718]
`yn` is very handy for copying filenames, but I've noticed that it's not compatible with `v`isual selection.

It would be nice to visually select a bunch of files, and then hit `yn` to copy the list of filenames to the clipboard.

Any ideas if this is possible, or perhaps something similar?

Basically, a selective `ls >> listFile`. I'm using that until I can find something more efficient.

**Comment by mrogalski** [comment]
`map yN  shell -f echo -n %%s | xsel -i; xsel -o | xsel -i -b`
the only difference between yn and this new yN is that yn uses %f and yN uses %s

**Comment by mrogalski** [comment]
BTW, watch out for spaces in the filenames -- with the previous bit of code, there is no real way of knowing where one filename ends and another begins.  You might want to put double quotes around %%s, like so:
`map yN shell -f echo -n "%%s" | xsel -i; xsel -o | xsel -i -b`
With this, however, You will always have quote marks around all filenames, which might be irritating in a different way.

**Comment by krompus** [comment]
Thanks for your response! I'm ideally looking for the filenames to be on different lines, as they are on the output of `ls >> listFile`.

**Comment by mrogalski** [comment]
The simplest way to do it is to pipe the echo into a `sed -e "s/' '/'\n'/g"`, although that is a ticking time bomb because it will fail if Your filename has the sequence `' '` in it.

The second simplest way is to write Your own plugin that does that almost correctly:
``` python
# Save the original macro function
import ranger.core.actions

old_get_macros = ranger.core.actions.Actions._get_macros


def get_macros_with_ls(self):
    macros = old_get_macros(self)
    macros['ls'] = ['\n'.join(macros['s'])]
    return macros

# Overwrite the old one
ranger.core.actions.Actions._get_macros = get_macros_with_ls
```

Put this into a file `~/.config/ranger/plugins/ls_macro.py`.  This should hopefully create a new macro %ls for this very purpose:
`map yN shell -f echo -n %%ls | xsel -i; xsel -o | xsel -i -b`
Notice that there are no double quotes around %%ls, as I see no quick and simple way to support escaping.  One could conceivably use `ranger.ext.shell_escape` in `get_macros_with_ls` to do this, but this might backfire in a situation where a thoughtless uses escapes surrounds the %ls with double quotes.  If this is necessary, I advise either adding an %lsescaped macro, or modifying the `substitute_macros` function from `ranger.core.actions` to support joining with newlines. 
Let vengeful gods of shell escaping help You if You want to make it foolproof, like supporting filenames with newlines.

**Comment by Q3CPMA** [comment]
What about `printf '%%s\n' %s` instead of `echo -n "%%s"`?

**Comment by mrogalski** [comment]
That doesn't work. `\n` doesn't affect the %s macro substitution in any way -- only a new line is added at the end of the text copied from ranger.

**Comment by Q3CPMA** [comment]
It provides a newline separated list for me (even with spaces in filenames). It's not what's wanted?

**Comment by krompus** [comment]
Can confirm; `map yN shell -f echo -n %%ls | xsel -i; xsel -o | xsel -i -b` does not function for me, but `printf '%%s\n' %s` does exactly what I am looking for.

Thank you both; very much appreciated!

The only nitpick I have now is that it seems to be preceded by a newline, and so when pasting in an empty vim file with `p`, for example, the paste starts on line 2. Of course, `P` fixes this, but it would be nice to fix that. :3

**Comment by Q3CPMA** [comment]
I suggest you git gud at shell, mate. Try `map yN shell -f printf '%%s\n' %s | head -c -1 | xsel -i; xsel -o | xsel -i -b` to remove your last '\n'. Also, I suggest you don't use echo unless you know when it's okay to use it.
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/echo.html

**Comment by Q3CPMA** [comment]
(if someone can replace head -c by something POSIX, I'm interested)

**Comment by krompus** [comment]
Perfect! Thanks!

Yeah, I'm always trying to git gud. Still a scrub. :)

**Comment by Q3CPMA** [comment]
You can replace `head -c 1` by `sed '$ s#.$##'` for POSIX compatibility.

**Comment by nfnty** [comment]
Added the mapping to the default `rc.conf`. Thanks!
