### ISSUE TITLE
Macros (like %s) don't work when they used in aliases in rc.conf

### ISSUE THREAD

**Issue by spcmd** [ranger/ranger#732]
So, after the upgrade to ranger-git (1.7.2.406.g496b1c0-1) from the stable (1.7.2-1), I have problems with the macros in my `rc.conf`, for example the `%s` doesn't get converted to the selected filename(s) when used in an alias.

Examples: 

`alias XX shell chmod +x %s` doesn't work: `chmod: cannot access '%s': No such file or directory`
Also tried with `%%s` or with quotes `"%%s"` or `"%s"` but none of them works.

`alias extract shell atool -xe %s` then running the extract on a file: `atool: %s: no such file and cannot identify format from extension`

These commands work fine when they typed in ranger with shell command (hitting  the **s** key) or when they mapped to a key, for example:

`map X shell chmod +x %s`
**or**
`map X shell atool -xe %s`

They work. 

But they don't work when they used in aliases in the rc.conf.

**Comment by hushpiper** [comment]
I am also seeing this issue on 1.8.1: aliases which worked previously no longer work. It looks like the macros are not getting expanded, as attempting to use the aliases to open these files gives errors like "/path/to/file/%f does not exist.", rather than referencing "/path/to/file/name". My aliases are pretty simple:

```
alias csv shell -f libreoffice --calc %f
alias lilypond shell -f lilypond %f
alias caja shell -f caja %d
```

Running the "alias" command with those arguments directly after opening ranger works just fine, and mapping works fine as well. It's just "alias" in rc.conf specifically that has issues.

**Comment by Vifon** [comment]
In aliases it might be needed to use double escaping, i.e. `alias csv shell -f libreoffice --calc %%f`. Can you try this? I don't remember the exact commit but the config line parsing procedure must have been changed.

**Comment by spcmd** [comment]
@Vifon : it doesn't work, I already tried that as you can see it in my opening comment.
