### ISSUE TITLE
Split View

### ISSUE THREAD

**Issue by hut** [ranger/ranger#82]
We need a midnight-commander-like split view.  There has been some talk about it already [1] but nobody started to implement it yet

[1] http://lists.nongnu.org/archive/html/ranger-users/2013-02/msg00006.html

**Comment by mox-mox** [comment]
There might be an easier to implement alternative here:
Have a way of yanking/copying/pasting to the system clipboard. This way, you can just have two windows of ranger beside each other.

**Comment by mox-mox** [comment]
But I would definitely like to have one of those possibilities!

**Comment by hut** [comment]
That doesn't work when using ranger over SSH, as far as I can see :|

**Comment by anonimal** [comment]
Before I open another ticket for a feature request along these lines, speaking of MC, if a split-view PLUS shell feature were implemented, I think it would help tremendously since the shell locks-in with the current working directory. This is huge for productivity, IMHO. The shell would have the ability to take up (at most) the bottom half of the screen (adjustable) so you can continue to browse and preview while working on a file. Also by default, any files opened would then go directly to that bottom panel/shell which would open the new vim instance instead of a new vim instance that commandeers ranger (this is what is currently in place).

Should I open a new ticket or does this make sense? Or did I not pay attention enough and ranger is already capable of such a thing? (By the way, ranger will be my new hero if these new features (or the shell feature) could be implemented).

**Comment by hut** [comment]
You can open a ticket if you want, and maybe someone will implement it, and it will not be me. But there are always resourceful people out there looking for a challenge. Maybe you get lucky.

**Comment by tex** [comment]
Yanking into clipboard is not good enough. Insteadm just share this data in some temporary? file (or shared memory?) on filesystem. This way it will be available even for multiple ssh sessions.

**Comment by cherti** [comment]
Is this still pending with viewmode multipane? Or has it just not been closed yet?

**Comment by nfnty** [comment]
Thanks for notifying; this has been resolved.

**Comment by mox-mox** [comment]
So is it working now, or have we just accepted that it will not be implemented in the near future?

**Comment by nfnty** [comment]
It's fully implemented and working since `1.8.0`. `viewmode` toggling is mapped to `~` by default and can be switched permanently in the config. Read the default config for more info.

**Comment by mox-mox** [comment]
Wow! Neat!

**Comment by Whyglobaleyes** [comment]
@nfnty Thanks for leaving the tip about viewmode & tilda. I've never muscle memorised MC but live in ranger so this has just improved my life superbly!!
