### ISSUE TITLE
Whole system search command needed

### ISSUE THREAD

**Issue by hamidrezakp** [ranger/ranger#882]
#### ISSUE TYPE

- Improvement/feature request

#### RUNTIME ENVIRONMENT

- Operating system and version: Ubuntu 16.04
- Terminal emulator and version: urxvt
- Python version: 3.5
- Ranger version/commit: 1.9
- Locale: en

#### EXPECTED BEHAVIOR

I need a search command to search a file in whole system and then list all result and i open the file or file location directory .

**Comment by eoyslebo** [comment]
+1, but I would like to use a cached list of files/folders. Cache could be a text file generated by find, or based on something like the mlocate.db file.

Use case is searching for a file/folder on a bunch of slow network shares. Currently using flat -1 and zh to filter, but it takes a really long time.

Ideally I want to specify a list of paths to generate a cache for, and how deep to index each path.

**Comment by toonn** [comment]
Check out [this wiki section](https://github.com/ranger/ranger/wiki/Integration-with-other-programs#search--shell-navigation) and [this one](https://github.com/ranger/ranger/wiki/Custom-Commands#search--navigation) for ways to do this. I personally wrote and use the `fd` integration.

Because this is such an old issue without activity I'm closing this. Feel free to reopen if you feel like the feature's still missing.
