### ISSUE TITLE
save_tabs_on_exit - Strange behaviour

### ISSUE THREAD

**Issue by tigerjack** [ranger/ranger#883]
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Operating system and version:  Ubuntu 14.04 x64
- Terminal emulator and version: gnome-terminal, konsole
- Python version: 2.7.6 
- Ranger version/commit: 1.9.0b5
- Locale: None.None

#### STEPS TO REPRODUCE
1. start ranger
2. open TabA, TabB, TabC 
3. press F10 to quit the session.
4. launch again a ranger session  from a random location, say `~`

#### EXPECTED BEHAVIOR
It should reopen TabA, TabB and TabC

#### CURRENT BEHAVIOR
It opens: Tab pointing at `~`, TabB, TabC.
So, TabA is lost and replaced by a tab pointing at the current location.

**Comment by ltgouvea** [comment]
Same behaviour occurs w/ Python v3.6.3 and termite

**Comment by mxovd** [comment]
This is the expected behavior according to the documentation. The active tab is not saved.
> Save all tabs, except the active, on exit

I think a more intuitive behavior would be:
on exit: tabA, tabB, tabC
launch ranger in ~/
on launch: ~, tabA, tabB, tabC

The tabs position will shift but they will all be restored

**Comment by toonn** [comment]
Not sure why you'd want to shift the tabs?
Imo most obvious/useful behavior would be to just restore the tabs unless an explicit path is passed, then restore the tabs and open the path in a new tab and focus that tab.
Couple difficulties though:
1. Tabs are limited so what would you do when there's already 9 tabs saved?
2. We allow "gaps" in the tabs so you could have only tabs 1 and 9, then what happens, shift the last tab, use the first available, last available?

**Comment by mxovd** [comment]
You mean restore the tabs at their original position? 
The current behavior already shifts the tabs, but without saving/restoring the active tab, which i'm not really sure why. I though that it was because the initial tabs always needed to be the first tab

But I think the behavior you described is probably optimal.

1) It seems like you can get more than 9 tabs. I got up to 30 tabs using the behavior i described, you can't access them with alt but you can with tab. I don't know if there are any other side effect to this.

2)I think the first available  would make more sense

**Comment by mxovd** [comment]
I removed the condition to disregard the current tab when saving tabs.
I then opened 9 tabs then quit and restart ranger a bunch of times. I was expecting an index error at some point, but it seems to be working.
https://github.com/ranger/ranger/blob/a30b5e5b517a04f35e79a41a624aaedf187f6a36/ranger/core/fm.py#L427-L428

**Comment by toonn** [comment]
You're right it does seem to just work™. I indeed get more than 9 tabs this way. Only quirk is that the new tab is opened at index 1 instead of the last but that's not a big enough deal to complicate this. I'm actually not really sure why `tab_new` limits to 9 tabs by default.

**Comment by mxovd** [comment]
@toonn Do you think tab index saving is still needed? (so that the tab layout is restored verbatim on launch)

**Comment by toonn** [comment]
Well, ideally yes. I didn't look into it yet though. I remember a recent PR that did something related.

**Comment by prosoitos** [comment]
Maybe the active tab was not saved on exit to avoid having a growing number of tabs for the current path if ranger is closed and re-opened multiple times?

I was about to open an issue reporting that the current tab was copied at each close/re-start of ranger, but reading this issue made me realize that it is not copied, it is just saved and then re-opened anew due to the change made following this issue.

If ranger gets re-opened from the path of the current tab, then the old behaviour makes more sense to avoid having duplicated tabs.

**Comment by toonn** [comment]
I actually agree neither is great. Maybe we should open the first tab with a matching path and only open a new one if there's no match? Don't think anyone could have any objections to this?

**Comment by prosoitos** [comment]
I think that it would be great! :slightly_smiling_face:
