### ISSUE TITLE
Speeding up on embedded device

### ISSUE THREAD

**Issue by ralesi** [ranger/ranger#946]
I installed the most recent HEAD from this repo to my QNAP NAS.  I  first installed Entware-NG, which is typically used for embedded devices to get python3 and dependencies installed.  

This device has a small ARM processor with basically no RAM to speak of, so obviously running something like `ranger` is somewhat slow, as to be expected.  

The question is as to whether there are any common options I can set up in the config to speed up my file navigation a bit.  

Thanks

**Comment by hut** [comment]
I just added a section on this to the FAQ:

https://github.com/ranger/ranger/wiki/FAQ:-Frequently-Asked-Questions#ranger-is-slow-how-to-improve-performance

I'm closing this issue because this is more like a discussion rather than a bug, and github's issue tracker is not really the place for it. Check out ranger's mailing list. :)
