### ISSUE TITLE
live search

### ISSUE THREAD

**Issue by plexigras** [ranger/ranger#956]
#### ISSUE TYPE
- Improvement/feature request

#### EXPECTED BEHAVIOR

search while typing

#### CURRENT BEHAVIOR

search after `<CR>`

#### CONTEXT

i would like to see search behave like in the video provided below

#### IMAGES / VIDEOS

https://asciinema.org/a/GKdug5BYueOhRv9LVtt5reWLr

**Comment by Vifon** [comment]
All the search commands are alieses to `:scout` with various flags. Specifically `-t` enables the behavior you described. I think we also by default have an alias called `:search_inc` which should be what you're looking for. Bind `:search_inc` instead of `:search` in your config and that should be it.

**Comment by plexigras** [comment]
oh thats nice but i cant bind it it says it cant find the command

**Comment by plexigras** [comment]
ok thx thats nice
