### ISSUE TITLE
Traverse should allow backward traverse too

### ISSUE THREAD

**Issue by cym13** [ranger/ranger#965]
#### ISSUE TYPE

- Improvement/feature request

#### RUNTIME ENVIRONMENT

- Operating system and version: Arch Linux
- Terminal emulator and version: Urxvt
- Python version: 3.6.2 (default, Jul 20 2017, 03:52:27) [GCC 7.1.1 20170630]
- Ranger version/commit: ranger-master 1.9.0b5
- Locale: en_US.UTF-8

#### CURRENT BEHAVIOR

Ranger proposes depth-first directory navigation through "traverse". This navigates downward through directories.

#### EXPECTED BEHAVIOR

The downward direction is hardcoded in traverse(), but reverse (upward) traversal should be made possible in order to allow back-and-forth depth-first navigation.

#### CONTEXT

This makes traverse much less useful as going back is much more painful than it should be.

#### POSSIBLE SOLUTIONS

traverse() should take an argument indicating the direction.

**Comment by toonn** [comment]
Consider ranger's history motions H and L in the meantime.

**Comment by toonn** [comment]
Thinking about this, how is going back up painful? It's *just* repeated presses of `h`.
The reverse of traverse would still be depth-first navigation but going up instead of down, imo. Note that this doesn't mean going up in the hierarchy, it's still going down the hierarchy but in the other direction.
In ranger terminology going "down the hierarchy" is going right, going "up the hierarchy" is going left, up and down are movements at a constant depth in the hierarchy.

**Comment by cym13** [comment]
Going back up pressing h was never the point. It's about traversing subdirectories in reverse order.

Depth-first going up... yeah, that sounds like it. Depth first, same root, taking children in reverse.
