### ISSUE TITLE
icat preview image method (suggestion/enhancement)

### ISSUE THREAD

**Issue by JackofSpades707** [ranger/ranger#983]
#### ISSUE TYPE
- Improvement/feature request

#### EXPECTED BEHAVIOR

A picture is worth a thousand words, I've linked to one at the bottom of this post

#### CURRENT BEHAVIOR

Better image rendering within the terminal

#### CONTEXT

Better overall Terminal Experience

#### POSSIBLE SOLUTIONS

Modify the rc.conf setting to use icat

#### IMAGES / VIDEOS

![image](https://user-images.githubusercontent.com/17239750/33530989-18b1d5e4-d83c-11e7-9189-ae1e53b55c85.png)
You may also be interested in these links : 
https://github.com/kovidgoyal/kitty/issues/33
https://github.com/kovidgoyal/kitty/blob/master/graphics-protocol.asciidoc

**Comment by soredake** [comment]
@hut
kitty recently gained support of specifying display region and clearing displayed images
https://github.com/kovidgoyal/kitty/commit/0b3a5a7d4568aacc07096b0acfd992ab3f3e0c25
https://github.com/kovidgoyal/kitty/commit/945613555a1ab413dc37209817936b12342b1cc4

https://github.com/kovidgoyal/kitty/issues/228#issuecomment-352173562

**Comment by toonn** [comment]
@soredake Does icat work on terminals other than kitty, how about inside of tmux? If it does then implementing kitty's graphics protocol for ranger might be worth the effort. So far we've avoided doing image previews with anything more than a program called from `scope.sh` because there just hasn't been a universal method that just works. We don't want to get stuck maintaining some custom hack with similar failings to w3mimgdisplay.

**Comment by mark-dawn** [comment]
I have spent some days implementing this for myself and I got it to work with reasonable performance.
I am using directly kitty's image protocol instead of kitty's icat, which misbehaves with some sizes.
![kittyranger](https://user-images.githubusercontent.com/36431389/36131892-819b9a7a-1074-11e8-80e3-a5cf97e4f380.jpg)
I think there are two main problems with this system: first, I used **PIL/pillow** to resize and convert images, which is not a dependency right now (w3m is external and other terminals accept different filetypes). However it doesn't seem unreasonable to ask for an image library if the user is interested in images, and I was planning of implementing a fallback to ImageMagick too.
Second, there is a nasty bug when scrolling very fast in a directory full of pics, where kitty's response fails to be caught and leaks into stdin, where the leading  `\033` corrupts the terminal quite badly. I am unsure if I can fix this on my end, but it might be possible to ask kovidgoyal to implement a command to suppress responses in the protocol.
Anyway I'll try forking/uploading the code somehow tomorrow, I am too tired for today

**Comment by mark-dawn** [comment]
FYI, I have a branch in my repository with what I currently have, if someone wants to check it out. Technically speaking everything is ready for a merge, I just need to finish filling up the pull request; but I'd like to check kitty's codebase to see if I could implement the fix and discuss it with kovidgoyal, and if it can be resolved quickly I would wait before merging it with the master branch. After all it's not nice to have the manpage mentioning that a feature has a bug.

**Comment by toonn** [comment]
Would appreciate kitty users to test that PR.

**Comment by CosmoJG** [comment]
@toonn Thank you so much for the pull request! I'm running the latest release of Ranger (1.9.1) on Kitty (0.12.0) on XWayland (1.20.1) on Sway (0.15.2) on Arch Linux. I also have python-pillow (5.2.0) installed. With both "set preview_images true" and "set preview_images_method kitty" in my rc.conf, nothing is displayed when previewing images (tested with PNGs).

Kitty's icat works just fine, but Ranger's image previews don't. Am I doing something wrong? Do I need to set additional config options?

**Comment by toonn** [comment]
@CosmoJG, not doing anything wrong except this is gonna be in the *next* release. On arch you can already get it by installing ranger-git from the AUR, that installs the head of the master branch. We keep master in working condition but breakages do creep in occasionally (mostly when I push to master x )).

**Comment by CosmoJG** [comment]
@toonn Ahh, thanks a million for the prompt reply! Keep up the awesome work. :)

**Comment by nicoulaj** [comment]
I just tested it with kitty 0.12.1, it mostly works but I could see a few bugs:

 * the images are offset (see screenshot)
 * sometimes the image blinks and disappears
 * moving the focus to another window makes the image disappear
 * resizing the window makes the image disappear

![screenshot_18-09-18_21 32 31](https://user-images.githubusercontent.com/3162/45711975-6be7c600-bb8b-11e8-83d6-b9e8e8e9d29d.png)

**Comment by mark-dawn** [comment]
@nicoulaj Did you set the image preview method to kitty? The issues you describe seems the same when w3m is used with kitty. You can set the preview type temporarily without changing your config using the command `:set preview_images_method kitty`

**Comment by nicoulaj** [comment]
@mark-dawn indeed, it works perfectly now!

**Comment by mark-dawn** [comment]
Also @nicoulaj, you should append `kitty` to your `$TERM` environment variable. Sadly I haven't found a better way to test if your actual terminal emulator is kitty except asking manual intent from the user. It's a bit annoying but without it that ranger freezes, and I prefer not to lock people in a tty when launching ranger during some emergency situation.

**Comment by nicoulaj** [comment]
It's already this way, kitty sets it to `xterm-kitty`. But my ranger config explicitly contained `set preview_images_method w3m`, so I guess it's fine in this case.

**Comment by toonn** [comment]
Closing because the feature has been released.

**Comment by dufferzafar** [comment]
@toonn Which ranger version has this? I'm running ranger 1.9.2 and can't get image previews to work.

**Comment by dufferzafar** [comment]
This was because I was using a very old `scope.sh` file. I had some of my customizations in there. I copied the scope file from GitHub and things worked!

**Comment by dufferzafar** [comment]
I came back to my ranger config and I'm noticing something weird. Image previews stop working when I set preview method to kitty, but otherwise work fine!

Preview doesn't work when I have this in config (tested on both Kitty & ranger):

```ini
set preview_images true
set preview_images_method kitty
```

But work fine, when I just keep it like:


```ini
set preview_images true
# set preview_images_method kitty
```

**Comment by toonn** [comment]
Do you have PIL (pillow) installed for your python? That's a requirement for kitty previews. Konsole might work with w3m and would probably work with ueberzug.

**Comment by dufferzafar** [comment]
@toonn Yes, I do have pillow installed. Just ran `pacman -S python-pillow` and conirmed.

**Comment by toonn** [comment]
I'm out of ideas. You're not running inside tmux, are you? The kitty image preview method only works if "kitty" is a substring of `TERM`.

**Comment by dufferzafar** [comment]
This was it. I was manually setting TERM to be `xterm-256color` in my .zshrc

Fixed it. Thanks.

**Comment by dufferzafar** [comment]
@toonn is there any way i can get kitty preview method, while still having my `TERM` set to `xterm-256color`?

using `xterm-kitty` as  my term breaks a lot of the other tools, and instead of trying to fix all of them, i'm thinking maybe i could get ranger working?

**Comment by toonn** [comment]
@dufferzafar, the only working solution for now is `TERM=xterm-kitty`, whenever you ssh use `env TERM=xterm-256color ssh` instead, then if you want previews on the remote ssh side too use `env TERM=xterm-kitty ranger`. You can probably alias these or put them in scripts to reduce typing, or use fish its history completion makes this pretty painless.

I know this isn't ideal but the kitty image preview method needs to be restricted to kitty terminals otherwise you'd get a corrupted ranger and this is the only way to detect what terminal you're running in. If you find a better solution I'd love to know.

**Comment by LRitzdorf** [comment]
Quick note, for anyone reading this in the future: when the next release of Ranger happens, it'll include Kitty graphics auto-detection #3036, rather than relying on `$TERM`. That should be any version after v1.9.4.

**Comment by jakob1379** [comment]
for any `nix`/`home-manager` users, this works:
```nix
programs.ranger = {
  enable = true;
  extraPackages = [ pkgs.python313Packages.pillow ];
  settings = {
    preview_images = true;
    preview_images_method = "kitty";
  };
};
```
